"""
Code Generation Tools for AutoNinja

LangChain tools for generating Bedrock Agent configurations,
action groups, tool integrations, and deployment code.
"""

import json
import re
from typing import Dict, List, Any, Optional, Type
from langchain.tools import BaseTool
from pydantic import BaseModel, Field
from autoninja.core.knowledge_base import BedrockKnowledgeBaseClient, KnowledgeBaseType


class BedrockAgentConfigInput(BaseModel):
    """Input schema for Bedrock Agent configuration generation tool."""
    requirements: Dict[str, Any] = Field(description="Agent requirements and specifications")
    architecture: Dict[str, Any] = Field(description="Service architecture design")


class BedrockAgentConfigTool(BaseTool):
    """Tool for generating Bedrock Agent configurations."""
    
    name: str = "bedrock_agent_config_generator"
    description: str = """Generate complete Bedrock Agent configurations including
    agent definitions, action groups, and knowledge base integrations."""
    
    args_schema: Type[BaseModel] = BedrockAgentConfigInput
    kb_client: Optional[BedrockKnowledgeBaseClient] = Field(default=None, exclude=True)
    
    def __init__(self, knowledge_base_client: Optional[BedrockKnowledgeBaseClient] = None, **kwargs):
        super().__init__(kb_client=knowledge_base_client, **kwargs)
   
    def _run(self, requirements: Dict[str, Any], architecture: Dict[str, Any]) -> str:
        """Generate Bedrock Agent configuration."""
        try:
            # Generate agent configuration
            agent_config = self._generate_agent_config(requirements, architecture)
            
            # Generate action groups
            action_groups = self._generate_action_groups(requirements, architecture)
            
            # Generate knowledge base configuration
            kb_config = self._generate_knowledge_base_config(requirements)
            
            # Get code templates from knowledge base
            code_templates = []
            if self.kb_client:
                code_templates = self._get_code_templates(requirements)
            
            result = {
                "agent_configuration": agent_config,
                "action_groups": action_groups,
                "knowledge_base_configuration": kb_config,
                "code_templates": code_templates,
                "deployment_artifacts": self._generate_deployment_artifacts(agent_config, action_groups)
            }
            
            return json.dumps(result, indent=2)
            
        except Exception as e:
            return f"Error generating Bedrock Agent configuration: {str(e)}"
    
    def _generate_agent_config(self, requirements: Dict[str, Any], architecture: Dict[str, Any]) -> Dict[str, Any]:
        """Generate Bedrock Agent configuration."""
        agent_type = requirements.get("agent_type_detected", "custom")
        functional_reqs = requirements.get("functional_requirements", [])
        
        # Determine foundation model based on complexity
        complexity = self._assess_complexity(functional_reqs)
        foundation_model = self._select_foundation_model(complexity)
        
        agent_config = {
            "agent_name": f"AutoNinja-{agent_type.title()}-Agent",
            "description": f"AI agent for {agent_type} tasks generated by AutoNinja",
            "foundation_model": foundation_model,
            "instruction": self._generate_agent_instruction(requirements),
            "idle_session_ttl_in_seconds": 3600,
            "agent_resource_role_arn": "arn:aws:iam::ACCOUNT:role/AmazonBedrockExecutionRoleForAgents_SUFFIX",
            "customer_encryption_key_arn": None,
            "tags": {
                "CreatedBy": "AutoNinja",
                "AgentType": agent_type,
                "Environment": "production"
            }
        }
        
        return agent_config

    def _generate_action_groups(self, requirements: Dict[str, Any], architecture: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Generate action groups for the Bedrock Agent."""
        action_groups = []
        functional_reqs = requirements.get("functional_requirements", [])
        
        # Core action group for basic functionality
        core_actions = self._generate_core_action_group(functional_reqs)
        action_groups.append(core_actions)
        
        # Data processing action group if needed
        if any("data" in req.lower() or "process" in req.lower() for req in functional_reqs):
            data_actions = self._generate_data_action_group(functional_reqs)
            action_groups.append(data_actions)
        
        # Integration action group if needed
        if any("integrate" in req.lower() or "api" in req.lower() for req in functional_reqs):
            integration_actions = self._generate_integration_action_group(functional_reqs)
            action_groups.append(integration_actions)
        
        return action_groups

    def _generate_core_action_group(self, functional_reqs: List[str]) -> Dict[str, Any]:
        """Generate core action group with basic functionality."""
        return {
            "action_group_name": "CoreActions",
            "description": "Core functionality for the AI agent",
            "parent_action_group_signature": "AMAZON.UserInput",
            "action_group_executor": {
                "lambda": {
                    "lambda_arn": "arn:aws:lambda:REGION:ACCOUNT:function:agent-core-actions"
                }
            },
            "api_schema": {
                "payload": json.dumps({
                    "openapi": "3.0.0",
                    "info": {
                        "title": "Core Actions API",
                        "version": "1.0.0",
                        "description": "Core functionality for the AI agent"
                    },
                    "paths": {
                        "/process_request": {
                            "post": {
                                "description": "Process user requests and generate responses",
                                "parameters": [
                                    {
                                        "name": "user_input",
                                        "in": "query",
                                        "description": "User input to process",
                                        "required": True,
                                        "schema": {"type": "string"}
                                    }
                                ],
                                "responses": {
                                    "200": {
                                        "description": "Successful response",
                                        "content": {
                                            "application/json": {
                                                "schema": {
                                                    "type": "object",
                                                    "properties": {
                                                        "response": {"type": "string"},
                                                        "confidence": {"type": "number"}
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                })
            },
            "action_group_state": "ENABLED"
        }

    def _generate_data_action_group(self, functional_reqs: List[str]) -> Dict[str, Any]:
        """Generate data processing action group."""
        return {
            "action_group_name": "DataActions",
            "description": "Data processing and management functionality",
            "action_group_executor": {
                "lambda": {
                    "lambda_arn": "arn:aws:lambda:REGION:ACCOUNT:function:agent-data-actions"
                }
            },
            "api_schema": {
                "payload": json.dumps({
                    "openapi": "3.0.0",
                    "info": {
                        "title": "Data Actions API",
                        "version": "1.0.0"
                    },
                    "paths": {
                        "/store_data": {
                            "post": {
                                "description": "Store data in the system",
                                "parameters": [
                                    {
                                        "name": "data",
                                        "in": "query",
                                        "description": "Data to store",
                                        "required": True,
                                        "schema": {"type": "string"}
                                    }
                                ]
                            }
                        },
                        "/retrieve_data": {
                            "get": {
                                "description": "Retrieve stored data",
                                "parameters": [
                                    {
                                        "name": "query",
                                        "in": "query",
                                        "description": "Query for data retrieval",
                                        "required": True,
                                        "schema": {"type": "string"}
                                    }
                                ]
                            }
                        }
                    }
                })
            },
            "action_group_state": "ENABLED"
        }
   
    def _generate_integration_action_group(self, functional_reqs: List[str]) -> Dict[str, Any]:
        """Generate integration action group."""
        return {
            "action_group_name": "IntegrationActions",
            "description": "External system integration functionality",
            "action_group_executor": {
                "lambda": {
                    "lambda_arn": "arn:aws:lambda:REGION:ACCOUNT:function:agent-integration-actions"
                }
            },
            "api_schema": {
                "payload": json.dumps({
                    "openapi": "3.0.0",
                    "info": {
                        "title": "Integration Actions API",
                        "version": "1.0.0"
                    },
                    "paths": {
                        "/call_external_api": {
                            "post": {
                                "description": "Call external API endpoints",
                                "parameters": [
                                    {
                                        "name": "endpoint",
                                        "in": "query",
                                        "description": "API endpoint to call",
                                        "required": True,
                                        "schema": {"type": "string"}
                                    },
                                    {
                                        "name": "payload",
                                        "in": "query",
                                        "description": "Request payload",
                                        "required": False,
                                        "schema": {"type": "string"}
                                    }
                                ]
                            }
                        }
                    }
                })
            },
            "action_group_state": "ENABLED"
        }
  
    def _generate_knowledge_base_config(self, requirements: Dict[str, Any]) -> Dict[str, Any]:
        """Generate knowledge base configuration."""
        agent_type = requirements.get("agent_type_detected", "custom")
        
        return {
            "knowledge_base_id": f"autoninja-{agent_type}-kb",
            "description": f"Knowledge base for {agent_type} agent",
            "knowledge_base_state": "ENABLED",
            "data_source_configuration": {
                "type": "S3",
                "s3_configuration": {
                    "bucket_arn": "arn:aws:s3:::autoninja-knowledge-base",
                    "inclusion_prefixes": [f"{agent_type}/"]
                }
            },
            "storage_configuration": {
                "type": "OPENSEARCH_SERVERLESS",
                "opensearch_serverless_configuration": {
                    "collection_arn": "arn:aws:aoss:REGION:ACCOUNT:collection/autoninja-kb",
                    "vector_index_name": f"autoninja-{agent_type}-index",
                    "field_mapping": {
                        "vector_field": "vector",
                        "text_field": "text",
                        "metadata_field": "metadata"
                    }
                }
            }
        }
   
    def _assess_complexity(self, functional_reqs: List[str]) -> str:
        """Assess complexity of requirements."""
        complex_indicators = ["analyze", "machine learning", "ai", "complex", "advanced", "intelligent"]
        
        complexity_score = 0
        for req in functional_reqs:
            req_lower = req.lower()
            complexity_score += sum(1 for indicator in complex_indicators if indicator in req_lower)
            complexity_score += len(req.split()) // 10  # Length factor
        
        if complexity_score >= 5:
            return "high"
        elif complexity_score >= 2:
            return "medium"
        else:
            return "low"
    
    def _select_foundation_model(self, complexity: str) -> str:
        """Select appropriate foundation model based on complexity."""
        if complexity == "high":
            return "anthropic.claude-3-opus-20240229-v1:0"
        elif complexity == "medium":
            return "anthropic.claude-3-sonnet-20240229-v1:0"
        else:
            return "anthropic.claude-3-haiku-20240307-v1:0"
  
    def _generate_agent_instruction(self, requirements: Dict[str, Any]) -> str:
        """Generate agent instruction based on requirements."""
        agent_type = requirements.get("agent_type_detected", "custom")
        functional_reqs = requirements.get("functional_requirements", [])
        
        base_instruction = f"You are a {agent_type} AI agent created by AutoNinja. "
        
        if agent_type == "conversational":
            base_instruction += "You excel at natural conversations and helping users with their questions and tasks. "
        elif agent_type == "analytical":
            base_instruction += "You specialize in data analysis, insights generation, and analytical reasoning. "
        elif agent_type == "automation":
            base_instruction += "You focus on automating tasks and workflows efficiently. "
        else:
            base_instruction += "You are designed to handle custom tasks as specified. "
        
        # Add specific capabilities
        if functional_reqs:
            capabilities = ", ".join(functional_reqs[:3])  # Top 3 requirements
            base_instruction += f"Your key capabilities include: {capabilities}. "
        
        base_instruction += "Always be helpful, accurate, and follow best practices. "
        base_instruction += "If you're unsure about something, ask for clarification rather than making assumptions."
        
        return base_instruction
    
    def _get_code_templates(self, requirements: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Get relevant code templates from knowledge base."""
        if not self.kb_client:
            return []
        
        try:
            agent_type = requirements.get("agent_type_detected", "custom")
            query = f"code templates for {agent_type} agent implementation"
            
            results = self.kb_client.search_knowledge_base(
                kb_type=KnowledgeBaseType.CODE_TEMPLATES,
                query=query,
                max_results=5
            )
            
            templates = []
            for result in results:
                templates.append({
                    "template_name": result.title,
                    "description": result.excerpt,
                    "relevance_score": result.relevance_score,
                    "content": result.content[:1000] + "..." if len(result.content) > 1000 else result.content
                })
            
            return templates
            
        except Exception:
            return []
  
    def _generate_deployment_artifacts(self, agent_config: Dict[str, Any], action_groups: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Generate deployment artifacts for the agent."""
        return {
            "lambda_functions": self._generate_lambda_functions(action_groups),
            "iam_policies": self._generate_iam_policies(agent_config, action_groups),
            "deployment_script": self._generate_deployment_script(agent_config, action_groups),
            "environment_variables": self._generate_environment_variables(agent_config)
        }
    
    def _generate_lambda_functions(self, action_groups: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Generate Lambda function code for action groups."""
        functions = []
        
        for action_group in action_groups:
            function_name = action_group["action_group_name"].lower().replace("actions", "_handler")
            
            function_code = f'''
import json
import boto3
import logging

logger = logging.getLogger()
logger.setLevel(logging.INFO)

def lambda_handler(event, context):
    """
    Lambda handler for {action_group["action_group_name"]}
    """
    try:
        # Extract action and parameters from event
        action = event.get("actionGroup", "")
        api_path = event.get("apiPath", "")
        parameters = event.get("parameters", [])
        
        logger.info(f"Processing action: {{action}}, path: {{api_path}}")
        
        # Route to appropriate handler
        if api_path == "/process_request":
            return handle_process_request(parameters)
        elif api_path == "/store_data":
            return handle_store_data(parameters)
        elif api_path == "/retrieve_data":
            return handle_retrieve_data(parameters)
        elif api_path == "/call_external_api":
            return handle_external_api(parameters)
        else:
            return {{
                "statusCode": 400,
                "body": json.dumps({{"error": "Unknown action path"}})
            }}
            
    except Exception as e:
        logger.error(f"Error processing request: {{str(e)}}")
        return {{
            "statusCode": 500,
            "body": json.dumps({{"error": "Internal server error"}})
        }}

def handle_process_request(parameters):
    """Handle process request action."""
    user_input = get_parameter_value(parameters, "user_input")
    
    # Process the user input (placeholder implementation)
    response = f"Processed: {{user_input}}"
    
    return {{
        "statusCode": 200,
        "body": json.dumps({{
            "response": response,
            "confidence": 0.95
        }})
    }}

def handle_store_data(parameters):
    """Handle store data action."""
    data = get_parameter_value(parameters, "data")
    
    # Store data implementation (placeholder)
    # In real implementation, would use DynamoDB or other storage
    
    return {{
        "statusCode": 200,
        "body": json.dumps({{"message": "Data stored successfully"}})
    }}

def handle_retrieve_data(parameters):
    """Handle retrieve data action."""
    query = get_parameter_value(parameters, "query")
    
    # Retrieve data implementation (placeholder)
    # In real implementation, would query database
    
    return {{
        "statusCode": 200,
        "body": json.dumps({{
            "data": f"Retrieved data for: {{query}}",
            "count": 1
        }})
    }}

def handle_external_api(parameters):
    """Handle external API call action."""
    endpoint = get_parameter_value(parameters, "endpoint")
    payload = get_parameter_value(parameters, "payload")
    
    # External API call implementation (placeholder)
    # In real implementation, would make HTTP requests
    
    return {{
        "statusCode": 200,
        "body": json.dumps({{
            "result": f"Called {{endpoint}} with payload: {{payload}}",
            "success": True
        }})
    }}

def get_parameter_value(parameters, name):
    """Extract parameter value by name."""
    for param in parameters:
        if param.get("name") == name:
            return param.get("value", "")
    return ""
'''
            
            functions.append({
                "function_name": function_name,
                "description": f"Lambda function for {action_group['description']}",
                "runtime": "python3.12",
                "handler": "index.lambda_handler",
                "code": function_code.strip(),
                "environment_variables": {
                    "LOG_LEVEL": "INFO",
                    "AGENT_NAME": "AutoNinja-Agent"
                }
            })
        
        return functions
 
    def _generate_iam_policies(self, agent_config: Dict[str, Any], action_groups: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Generate IAM policies for the agent."""
        policies = []
        
        # Agent execution role policy
        agent_policy = {
            "policy_name": "BedrockAgentExecutionPolicy",
            "description": "Policy for Bedrock Agent execution",
            "policy_document": {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Action": [
                            "bedrock:InvokeModel",
                            "bedrock:RetrieveAndGenerate",
                            "bedrock:Retrieve"
                        ],
                        "Resource": "*"
                    },
                    {
                        "Effect": "Allow",
                        "Action": [
                            "lambda:InvokeFunction"
                        ],
                        "Resource": "arn:aws:lambda:*:*:function:agent-*"
                    }
                ]
            }
        }
        policies.append(agent_policy)
        
        # Lambda execution policy
        lambda_policy = {
            "policy_name": "LambdaExecutionPolicy",
            "description": "Policy for Lambda function execution",
            "policy_document": {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Action": [
                            "logs:CreateLogGroup",
                            "logs:CreateLogStream",
                            "logs:PutLogEvents"
                        ],
                        "Resource": "arn:aws:logs:*:*:*"
                    },
                    {
                        "Effect": "Allow",
                        "Action": [
                            "dynamodb:GetItem",
                            "dynamodb:PutItem",
                            "dynamodb:UpdateItem",
                            "dynamodb:DeleteItem",
                            "dynamodb:Query",
                            "dynamodb:Scan"
                        ],
                        "Resource": "arn:aws:dynamodb:*:*:table/agent-*"
                    }
                ]
            }
        }
        policies.append(lambda_policy)
        
        return policies
   
    def _generate_deployment_script(self, agent_config: Dict[str, Any], action_groups: List[Dict[str, Any]]) -> str:
        """Generate deployment script for the agent."""
        script = f'''#!/bin/bash
# AutoNinja Agent Deployment Script
# Generated for: {agent_config["agent_name"]}

set -e

echo "Starting deployment of {agent_config['agent_name']}..."

# Variables
AGENT_NAME="{agent_config['agent_name']}"
REGION="us-east-2"
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

# Create IAM roles
echo "Creating IAM roles..."
aws iam create-role --role-name AmazonBedrockExecutionRoleForAgents_${{AGENT_NAME}} \\
    --assume-role-policy-document file://trust-policy.json

# Attach policies
aws iam attach-role-policy --role-name AmazonBedrockExecutionRoleForAgents_${{AGENT_NAME}} \\
    --policy-arn arn:aws:iam::aws:policy/AmazonBedrockFullAccess

# Deploy Lambda functions
echo "Deploying Lambda functions..."
'''
        
        for action_group in action_groups:
            function_name = action_group["action_group_name"].lower().replace("actions", "-handler")
            script += f'''
# Deploy {function_name}
zip -r {function_name}.zip index.py
aws lambda create-function \\
    --function-name agent-{function_name} \\
    --runtime python3.12 \\
    --role arn:aws:iam::$ACCOUNT_ID:role/lambda-execution-role \\
    --handler index.lambda_handler \\
    --zip-file fileb://{function_name}.zip
'''
        
        script += f'''
# Create Bedrock Agent
echo "Creating Bedrock Agent..."
aws bedrock-agent create-agent \\
    --agent-name "$AGENT_NAME" \\
    --foundation-model "{agent_config['foundation_model']}" \\
    --instruction "{agent_config['instruction']}" \\
    --agent-resource-role-arn "arn:aws:iam::$ACCOUNT_ID:role/AmazonBedrockExecutionRoleForAgents_${{AGENT_NAME}}"

echo "Deployment completed successfully!"
echo "Agent ARN: arn:aws:bedrock:$REGION:$ACCOUNT_ID:agent/$AGENT_NAME"
'''
        
        return script.strip()

    def _generate_environment_variables(self, agent_config: Dict[str, Any]) -> Dict[str, str]:
        """Generate environment variables for the agent."""
        return {
            "AGENT_NAME": agent_config["agent_name"],
            "FOUNDATION_MODEL": agent_config["foundation_model"],
            "AWS_REGION": "us-east-2",
            "LOG_LEVEL": "INFO",
            "ENVIRONMENT": "production"
        }


# For now, let's create a simple test to verify the basic functionality
if __name__ == "__main__":
    # Simple test
    tool = BedrockAgentConfigTool()
    
    test_requirements = {
        "agent_type_detected": "conversational",
        "functional_requirements": [
            "Handle customer inquiries",
            "Process data requests"
        ]
    }
    
    test_architecture = {
        "services": ["lambda", "dynamodb"],
        "complexity": "medium"
    }
    
    result = tool._run(test_requirements, test_architecture)
    print("✅ BedrockAgentConfigTool test passed!")
    print("Generated configuration length:", len(result))