"""
Code Generation Tools for AutoNinja

LangChain tools for generating Bedrock Agent configurations,
action groups, tool integrations, and deployment code.
"""

import json
import re
from typing import Dict, List, Any, Optional, Type
from langchain.tools import BaseTool
from pydantic import BaseModel, Field
from autoninja.core.knowledge_base import BedrockKnowledgeBaseClient, KnowledgeBaseType


class BedrockAgentConfigInput(BaseModel):
    """Input schema for Bedrock Agent configuration generation tool."""
    requirements: Dict[str, Any] = Field(description="Agent requirements and specifications")
    architecture: Dict[str, Any] = Field(description="Service architecture design")


class BedrockAgentConfigTool(BaseTool):
    """Tool for generating Bedrock Agent configurations."""
    
    name: str = "bedrock_agent_config_generator"
    description: str = """Generate complete Bedrock Agent configurations including
    agent definitions, action groups, and knowledge base integrations."""
    
    args_schema: Type[BaseModel] = BedrockAgentConfigInput
    kb_client: Optional[BedrockKnowledgeBaseClient] = Field(default=None, exclude=True)
    
    def __init__(self, knowledge_base_client: Optional[BedrockKnowledgeBaseClient] = None, **kwargs):
        super().__init__(kb_client=knowledge_base_client, **kwargs)     
   
    def _run(self, requirements: Dict[str, Any], architecture: Dict[str, Any]) -> str:
        """Generate Bedrock Agent configuration."""
        try:
            # Generate agent configuration
            agent_config = self._generate_agent_config(requirements, architecture)
            
            # Generate action groups
            action_groups = self._generate_action_groups(requirements, architecture)
            
            # Generate knowledge base configuration
            kb_config = self._generate_knowledge_base_config(requirements)
            
            # Get code templates from knowledge base
            code_templates = []
            if self.kb_client:
                code_templates = self._get_code_templates(requirements)
            
            result = {
                "agent_configuration": agent_config,
                "action_groups": action_groups,
                "knowledge_base_configuration": kb_config,
                "code_templates": code_templates,
                "deployment_artifacts": self._generate_deployment_artifacts(agent_config, action_groups)
            }
            
            return json.dumps(result, indent=2)
            
        except Exception as e:
            return f"Error generating Bedrock Agent configuration: {str(e)}"    
 
   def _generate_agent_config(self, requirements: Dict[str, Any], architecture: Dict[str, Any]) -> Dict[str, Any]:
        """Generate Bedrock Agent configuration."""
        agent_type = requirements.get("agent_type_detected", "custom")
        functional_reqs = requirements.get("functional_requirements", [])
        
        # Determine foundation model based on complexity
        complexity = self._assess_complexity(functional_reqs)
        foundation_model = self._select_foundation_model(complexity)
        
        agent_config = {
            "agent_name": f"AutoNinja-{agent_type.title()}-Agent",
            "description": f"AI agent for {agent_type} tasks generated by AutoNinja",
            "foundation_model": foundation_model,
            "instruction": self._generate_agent_instruction(requirements),
            "idle_session_ttl_in_seconds": 3600,
            "agent_resource_role_arn": "arn:aws:iam::ACCOUNT:role/AmazonBedrockExecutionRoleForAgents_SUFFIX",
            "customer_encryption_key_arn": None,
            "tags": {
                "CreatedBy": "AutoNinja",
                "AgentType": agent_type,
                "Environment": "production"
            }
        }
        
        return agent_config    

    def _generate_action_groups(self, requirements: Dict[str, Any], architecture: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Generate action groups for the Bedrock Agent."""
        action_groups = []
        functional_reqs = requirements.get("functional_requirements", [])
        
        # Core action group for basic functionality
        core_actions = self._generate_core_action_group(functional_reqs)
        action_groups.append(core_actions)
        
        # Data processing action group if needed
        if any("data" in req.lower() or "process" in req.lower() for req in functional_reqs):
            data_actions = self._generate_data_action_group(functional_reqs)
            action_groups.append(data_actions)
        
        # Integration action group if needed
        if any("integrate" in req.lower() or "api" in req.lower() for req in functional_reqs):
            integration_actions = self._generate_integration_action_group(functional_reqs)
            action_groups.append(integration_actions)
        
        return action_groups    

    def _generate_core_action_group(self, functional_reqs: List[str]) -> Dict[str, Any]:
        """Generate core action group with basic functionality."""
        return {
            "action_group_name": "CoreActions",
            "description": "Core functionality for the AI agent",
            "parent_action_group_signature": "AMAZON.UserInput",
            "action_group_executor": {
                "lambda": {
                    "lambda_arn": "arn:aws:lambda:REGION:ACCOUNT:function:agent-core-actions"
                }
            },
            "api_schema": {
                "payload": json.dumps({
                    "openapi": "3.0.0",
                    "info": {
                        "title": "Core Actions API",
                        "version": "1.0.0",
                        "description": "Core functionality for the AI agent"
                    },
                    "paths": {
                        "/process_request": {
                            "post": {
                                "description": "Process user requests and generate responses",
                                "parameters": [
                                    {
                                        "name": "user_input",
                                        "in": "query",
                                        "description": "User input to process",
                                        "required": True,
                                        "schema": {"type": "string"}
                                    }
                                ],
                                "responses": {
                                    "200": {
                                        "description": "Successful response",
                                        "content": {
                                            "application/json": {
                                                "schema": {
                                                    "type": "object",
                                                    "properties": {
                                                        "response": {"type": "string"},
                                                        "confidence": {"type": "number"}
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                })
            },
            "action_group_state": "ENABLED"
        }    

    def _generate_data_action_group(self, functional_reqs: List[str]) -> Dict[str, Any]:
        """Generate data processing action group."""
        return {
            "action_group_name": "DataActions",
            "description": "Data processing and management functionality",
            "action_group_executor": {
                "lambda": {
                    "lambda_arn": "arn:aws:lambda:REGION:ACCOUNT:function:agent-data-actions"
                }
            },
            "api_schema": {
                "payload": json.dumps({
                    "openapi": "3.0.0",
                    "info": {
                        "title": "Data Actions API",
                        "version": "1.0.0"
                    },
                    "paths": {
                        "/store_data": {
                            "post": {
                                "description": "Store data in the system",
                                "parameters": [
                                    {
                                        "name": "data",
                                        "in": "query",
                                        "description": "Data to store",
                                        "required": True,
                                        "schema": {"type": "string"}
                                    }
                                ]
                            }
                        },
                        "/retrieve_data": {
                            "get": {
                                "description": "Retrieve stored data",
                                "parameters": [
                                    {
                                        "name": "query",
                                        "in": "query",
                                        "description": "Query for data retrieval",
                                        "required": True,
                                        "schema": {"type": "string"}
                                    }
                                ]
                            }
                        }
                    }
                })
            },
            "action_group_state": "ENABLED"
        } 
   
    def _generate_integration_action_group(self, functional_reqs: List[str]) -> Dict[str, Any]:
        """Generate integration action group."""
        return {
            "action_group_name": "IntegrationActions",
            "description": "External system integration functionality",
            "action_group_executor": {
                "lambda": {
                    "lambda_arn": "arn:aws:lambda:REGION:ACCOUNT:function:agent-integration-actions"
                }
            },
            "api_schema": {
                "payload": json.dumps({
                    "openapi": "3.0.0",
                    "info": {
                        "title": "Integration Actions API",
                        "version": "1.0.0"
                    },
                    "paths": {
                        "/call_external_api": {
                            "post": {
                                "description": "Call external API endpoints",
                                "parameters": [
                                    {
                                        "name": "endpoint",
                                        "in": "query",
                                        "description": "API endpoint to call",
                                        "required": True,
                                        "schema": {"type": "string"}
                                    },
                                    {
                                        "name": "payload",
                                        "in": "query",
                                        "description": "Request payload",
                                        "required": False,
                                        "schema": {"type": "string"}
                                    }
                                ]
                            }
                        }
                    }
                })
            },
            "action_group_state": "ENABLED"
        }  
  
    def _generate_knowledge_base_config(self, requirements: Dict[str, Any]) -> Dict[str, Any]:
        """Generate knowledge base configuration."""
        agent_type = requirements.get("agent_type_detected", "custom")
        
        return {
            "knowledge_base_id": f"autoninja-{agent_type}-kb",
            "description": f"Knowledge base for {agent_type} agent",
            "knowledge_base_state": "ENABLED",
            "data_source_configuration": {
                "type": "S3",
                "s3_configuration": {
                    "bucket_arn": "arn:aws:s3:::autoninja-knowledge-base",
                    "inclusion_prefixes": [f"{agent_type}/"]
                }
            },
            "storage_configuration": {
                "type": "OPENSEARCH_SERVERLESS",
                "opensearch_serverless_configuration": {
                    "collection_arn": "arn:aws:aoss:REGION:ACCOUNT:collection/autoninja-kb",
                    "vector_index_name": f"autoninja-{agent_type}-index",
                    "field_mapping": {
                        "vector_field": "vector",
                        "text_field": "text",
                        "metadata_field": "metadata"
                    }
                }
            }
        } 
   
    def _assess_complexity(self, functional_reqs: List[str]) -> str:
        """Assess complexity of requirements."""
        complex_indicators = ["analyze", "machine learning", "ai", "complex", "advanced", "intelligent"]
        
        complexity_score = 0
        for req in functional_reqs:
            req_lower = req.lower()
            complexity_score += sum(1 for indicator in complex_indicators if indicator in req_lower)
            complexity_score += len(req.split()) // 10  # Length factor
        
        if complexity_score >= 5:
            return "high"
        elif complexity_score >= 2:
            return "medium"
        else:
            return "low"
    
    def _select_foundation_model(self, complexity: str) -> str:
        """Select appropriate foundation model based on complexity."""
        if complexity == "high":
            return "anthropic.claude-3-opus-20240229-v1:0"
        elif complexity == "medium":
            return "anthropic.claude-3-sonnet-20240229-v1:0"
        else:
            return "anthropic.claude-3-haiku-20240307-v1:0"  
  
    def _generate_agent_instruction(self, requirements: Dict[str, Any]) -> str:
        """Generate agent instruction based on requirements."""
        agent_type = requirements.get("agent_type_detected", "custom")
        functional_reqs = requirements.get("functional_requirements", [])
        
        base_instruction = f"You are a {agent_type} AI agent created by AutoNinja. "
        
        if agent_type == "conversational":
            base_instruction += "You excel at natural conversations and helping users with their questions and tasks. "
        elif agent_type == "analytical":
            base_instruction += "You specialize in data analysis, insights generation, and analytical reasoning. "
        elif agent_type == "automation":
            base_instruction += "You focus on automating tasks and workflows efficiently. "
        else:
            base_instruction += "You are designed to handle custom tasks as specified. "
        
        # Add specific capabilities
        if functional_reqs:
            capabilities = ", ".join(functional_reqs[:3])  # Top 3 requirements
            base_instruction += f"Your key capabilities include: {capabilities}. "
        
        base_instruction += "Always be helpful, accurate, and follow best practices. "
        base_instruction += "If you're unsure about something, ask for clarification rather than making assumptions."
        
        return base_instruction    
  
  def _get_code_templates(self, requirements: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Get relevant code templates from knowledge base."""
        if not self.kb_client:
            return []
        
        try:
            agent_type = requirements.get("agent_type_detected", "custom")
            query = f"code templates for {agent_type} agent implementation"
            
            results = self.kb_client.search_knowledge_base(
                kb_type=KnowledgeBaseType.CODE_TEMPLATES,
                query=query,
                max_results=5
            )
            
            templates = []
            for result in results:
                templates.append({
                    "template_name": result.title,
                    "description": result.excerpt,
                    "relevance_score": result.relevance_score,
                    "content": result.content[:1000] + "..." if len(result.content) > 1000 else result.content
                })
            
            return templates
            
        except Exception:
            return []  
  
    def _generate_deployment_artifacts(self, agent_config: Dict[str, Any], action_groups: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Generate deployment artifacts for the agent."""
        return {
            "lambda_functions": self._generate_lambda_functions(action_groups),
            "iam_policies": self._generate_iam_policies(agent_config, action_groups),
            "deployment_script": self._generate_deployment_script(agent_config, action_groups),
            "environment_variables": self._generate_environment_variables(agent_config)
        }
    
    def _generate_lambda_functions(self, action_groups: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Generate Lambda function code for action groups."""
        functions = []
        
        for action_group in action_groups:
            function_name = action_group["action_group_name"].lower().replace("actions", "_handler")
            
            function_code = f'''
import json
import boto3
import logging

logger = logging.getLogger()
logger.setLevel(logging.INFO)

def lambda_handler(event, context):
    """
    Lambda handler for {action_group["action_group_name"]}
    """
    try:
        # Extract action and parameters from event
        action = event.get("actionGroup", "")
        api_path = event.get("apiPath", "")
        parameters = event.get("parameters", [])
        
        logger.info(f"Processing action: {{action}}, path: {{api_path}}")
        
        # Route to appropriate handler
        if api_path == "/process_request":
            return handle_process_request(parameters)
        elif api_path == "/store_data":
            return handle_store_data(parameters)
        elif api_path == "/retrieve_data":
            return handle_retrieve_data(parameters)
        elif api_path == "/call_external_api":
            return handle_external_api(parameters)
        else:
            return {{
                "statusCode": 400,
                "body": json.dumps({{"error": "Unknown action path"}})
            }}
            
    except Exception as e:
        logger.error(f"Error processing request: {{str(e)}}")
        return {{
            "statusCode": 500,
            "body": json.dumps({{"error": "Internal server error"}})
        }}

def handle_process_request(parameters):
    """Handle process request action."""
    user_input = get_parameter_value(parameters, "user_input")
    
    # Process the user input (placeholder implementation)
    response = f"Processed: {{user_input}}"
    
    return {{
        "statusCode": 200,
        "body": json.dumps({{
            "response": response,
            "confidence": 0.95
        }})
    }}

def handle_store_data(parameters):
    """Handle store data action."""
    data = get_parameter_value(parameters, "data")
    
    # Store data implementation (placeholder)
    # In real implementation, would use DynamoDB or other storage
    
    return {{
        "statusCode": 200,
        "body": json.dumps({{"message": "Data stored successfully"}})
    }}

def handle_retrieve_data(parameters):
    """Handle retrieve data action."""
    query = get_parameter_value(parameters, "query")
    
    # Retrieve data implementation (placeholder)
    # In real implementation, would query database
    
    return {{
        "statusCode": 200,
        "body": json.dumps({{
            "data": f"Retrieved data for: {{query}}",
            "count": 1
        }})
    }}

def handle_external_api(parameters):
    """Handle external API call action."""
    endpoint = get_parameter_value(parameters, "endpoint")
    payload = get_parameter_value(parameters, "payload")
    
    # External API call implementation (placeholder)
    # In real implementation, would make HTTP requests
    
    return {{
        "statusCode": 200,
        "body": json.dumps({{
            "result": f"Called {{endpoint}} with payload: {{payload}}",
            "success": True
        }})
    }}

def get_parameter_value(parameters, name):
    """Extract parameter value by name."""
    for param in parameters:
        if param.get("name") == name:
            return param.get("value", "")
    return ""
'''
            
            functions.append({
                "function_name": function_name,
                "description": f"Lambda function for {action_group['description']}",
                "runtime": "python3.12",
                "handler": "index.lambda_handler",
                "code": function_code.strip(),
                "environment_variables": {
                    "LOG_LEVEL": "INFO",
                    "AGENT_NAME": "AutoNinja-Agent"
                }
            })
        
        return functions   
 
    def _generate_iam_policies(self, agent_config: Dict[str, Any], action_groups: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Generate IAM policies for the agent."""
        policies = []
        
        # Agent execution role policy
        agent_policy = {
            "policy_name": "BedrockAgentExecutionPolicy",
            "description": "Policy for Bedrock Agent execution",
            "policy_document": {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Action": [
                            "bedrock:InvokeModel",
                            "bedrock:RetrieveAndGenerate",
                            "bedrock:Retrieve"
                        ],
                        "Resource": "*"
                    },
                    {
                        "Effect": "Allow",
                        "Action": [
                            "lambda:InvokeFunction"
                        ],
                        "Resource": "arn:aws:lambda:*:*:function:agent-*"
                    }
                ]
            }
        }
        policies.append(agent_policy)
        
        # Lambda execution policy
        lambda_policy = {
            "policy_name": "LambdaExecutionPolicy",
            "description": "Policy for Lambda function execution",
            "policy_document": {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Action": [
                            "logs:CreateLogGroup",
                            "logs:CreateLogStream",
                            "logs:PutLogEvents"
                        ],
                        "Resource": "arn:aws:logs:*:*:*"
                    },
                    {
                        "Effect": "Allow",
                        "Action": [
                            "dynamodb:GetItem",
                            "dynamodb:PutItem",
                            "dynamodb:UpdateItem",
                            "dynamodb:DeleteItem",
                            "dynamodb:Query",
                            "dynamodb:Scan"
                        ],
                        "Resource": "arn:aws:dynamodb:*:*:table/agent-*"
                    }
                ]
            }
        }
        policies.append(lambda_policy)
        
        return policies    
   
 def _generate_deployment_script(self, agent_config: Dict[str, Any], action_groups: List[Dict[str, Any]]) -> str:
        """Generate deployment script for the agent."""
        script = f'''#!/bin/bash
# AutoNinja Agent Deployment Script
# Generated for: {agent_config["agent_name"]}

set -e

echo "Starting deployment of {agent_config['agent_name']}..."

# Variables
AGENT_NAME="{agent_config['agent_name']}"
REGION="us-east-2"
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)

# Create IAM roles
echo "Creating IAM roles..."
aws iam create-role --role-name AmazonBedrockExecutionRoleForAgents_${{AGENT_NAME}} \\
    --assume-role-policy-document file://trust-policy.json

# Attach policies
aws iam attach-role-policy --role-name AmazonBedrockExecutionRoleForAgents_${{AGENT_NAME}} \\
    --policy-arn arn:aws:iam::aws:policy/AmazonBedrockFullAccess

# Deploy Lambda functions
echo "Deploying Lambda functions..."
'''
        
        for action_group in action_groups:
            function_name = action_group["action_group_name"].lower().replace("actions", "-handler")
            script += f'''
# Deploy {function_name}
zip -r {function_name}.zip index.py
aws lambda create-function \\
    --function-name agent-{function_name} \\
    --runtime python3.12 \\
    --role arn:aws:iam::$ACCOUNT_ID:role/lambda-execution-role \\
    --handler index.lambda_handler \\
    --zip-file fileb://{function_name}.zip
'''
        
        script += f'''
# Create Bedrock Agent
echo "Creating Bedrock Agent..."
aws bedrock-agent create-agent \\
    --agent-name "$AGENT_NAME" \\
    --foundation-model "{agent_config['foundation_model']}" \\
    --instruction "{agent_config['instruction']}" \\
    --agent-resource-role-arn "arn:aws:iam::$ACCOUNT_ID:role/AmazonBedrockExecutionRoleForAgents_${{AGENT_NAME}}"

echo "Deployment completed successfully!"
echo "Agent ARN: arn:aws:bedrock:$REGION:$ACCOUNT_ID:agent/$AGENT_NAME"
'''
        
        return script.strip()    

    def _generate_environment_variables(self, agent_config: Dict[str, Any]) -> Dict[str, str]:
        """Generate environment variables for the agent."""
        return {
            "AGENT_NAME": agent_config["agent_name"],
            "FOUNDATION_MODEL": agent_config["foundation_model"],
            "AWS_REGION": "us-east-2",
            "LOG_LEVEL": "INFO",
            "ENVIRONMENT": "production"
        }


class ActionGroupGeneratorInput(BaseModel):
    """Input schema for action group generation tool."""
    functional_requirements: List[str] = Field(description="Functional requirements for action groups")
    integration_specs: Optional[Dict[str, Any]] = Field(default=None, description="Integration specifications")


class ActionGroupGeneratorTool(BaseTool):
    """Tool for generating Bedrock Agent action groups and tool integrations."""
    
    name: str = "action_group_generator"
    description: str = """Generate action groups and tool integrations for Bedrock Agents.
    Creates OpenAPI specifications and Lambda function implementations."""
    
    args_schema: Type[BaseModel] = ActionGroupGeneratorInput
    kb_client: Optional[BedrockKnowledgeBaseClient] = Field(default=None, exclude=True)
    
    def __init__(self, knowledge_base_client: Optional[BedrockKnowledgeBaseClient] = None, **kwargs):
        super().__init__(kb_client=knowledge_base_client, **kwargs) 
       
    def _run(self, functional_requirements: List[str], integration_specs: Optional[Dict[str, Any]] = None) -> str:
        """Generate action groups and tool integrations."""
        try:
            # Analyze requirements to determine action groups
            action_groups = self._analyze_and_generate_action_groups(functional_requirements)
            
            # Generate OpenAPI specifications
            api_specs = self._generate_api_specifications(action_groups)
            
            # Generate Lambda implementations
            lambda_implementations = self._generate_lambda_implementations(action_groups)
            
            # Generate integration code if specs provided
            integrations = []
            if integration_specs:
                integrations = self._generate_integrations(integration_specs)
            
            result = {
                "action_groups": action_groups,
                "api_specifications": api_specs,
                "lambda_implementations": lambda_implementations,
                "integrations": integrations,
                "deployment_guide": self._generate_deployment_guide(action_groups)
            }
            
            return json.dumps(result, indent=2)
            
        except Exception as e:
            return f"Error generating action groups: {str(e)}" 
   
    def _analyze_and_generate_action_groups(self, functional_requirements: List[str]) -> List[Dict[str, Any]]:
        """Analyze requirements and generate appropriate action groups."""
        action_groups = []
        
        # Categorize requirements
        categories = self._categorize_requirements(functional_requirements)
        
        for category, requirements in categories.items():
            if not requirements:
                continue
                
            action_group = {
                "name": f"{category.title()}Actions",
                "description": f"Action group for {category} functionality",
                "category": category,
                "actions": self._generate_actions_for_category(category, requirements)
            }
            action_groups.append(action_group)
        
        return action_groups
    
    def _categorize_requirements(self, requirements: List[str]) -> Dict[str, List[str]]:
        """Categorize functional requirements."""
        categories = {
            "data": [],
            "communication": [],
            "analysis": [],
            "automation": [],
            "integration": [],
            "general": []
        }
        
        for req in requirements:
            req_lower = req.lower()
            
            if any(word in req_lower for word in ["data", "store", "retrieve", "database", "save"]):
                categories["data"].append(req)
            elif any(word in req_lower for word in ["email", "message", "notify", "send", "communicate"]):
                categories["communication"].append(req)
            elif any(word in req_lower for word in ["analyze", "report", "calculate", "process", "compute"]):
                categories["analysis"].append(req)
            elif any(word in req_lower for word in ["automate", "schedule", "trigger", "workflow"]):
                categories["automation"].append(req)
            elif any(word in req_lower for word in ["integrate", "api", "connect", "external"]):
                categories["integration"].append(req)
            else:
                categories["general"].append(req)
        
        return categories    

    def _generate_actions_for_category(self, category: str, requirements: List[str]) -> List[Dict[str, Any]]:
        """Generate specific actions for a category."""
        actions = []
        
        if category == "data":
            actions.extend([
                {
                    "name": "store_data",
                    "description": "Store data in the system",
                    "parameters": [
                        {"name": "data", "type": "string", "required": True, "description": "Data to store"},
                        {"name": "key", "type": "string", "required": False, "description": "Storage key"}
                    ]
                },
                {
                    "name": "retrieve_data",
                    "description": "Retrieve stored data",
                    "parameters": [
                        {"name": "query", "type": "string", "required": True, "description": "Query for data retrieval"}
                    ]
                }
            ])
        
        elif category == "communication":
            actions.extend([
                {
                    "name": "send_notification",
                    "description": "Send notifications to users",
                    "parameters": [
                        {"name": "message", "type": "string", "required": True, "description": "Message to send"},
                        {"name": "recipient", "type": "string", "required": True, "description": "Recipient identifier"}
                    ]
                }
            ])
        
        elif category == "analysis":
            actions.extend([
                {
                    "name": "analyze_data",
                    "description": "Perform data analysis",
                    "parameters": [
                        {"name": "dataset", "type": "string", "required": True, "description": "Dataset to analyze"},
                        {"name": "analysis_type", "type": "string", "required": False, "description": "Type of analysis"}
                    ]
                }
            ])
        
        elif category == "integration":
            actions.extend([
                {
                    "name": "call_external_api",
                    "description": "Call external API endpoints",
                    "parameters": [
                        {"name": "endpoint", "type": "string", "required": True, "description": "API endpoint URL"},
                        {"name": "method", "type": "string", "required": False, "description": "HTTP method"},
                        {"name": "payload", "type": "string", "required": False, "description": "Request payload"}
                    ]
                }
            ])
        
        else:  # general
            actions.append({
                "name": "process_request",
                "description": "Process general user requests",
                "parameters": [
                    {"name": "request", "type": "string", "required": True, "description": "User request to process"}
                ]
            })
        
        return actions    

    def _generate_api_specifications(self, action_groups: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Generate OpenAPI specifications for action groups."""
        api_specs = []
        
        for group in action_groups:
            spec = {
                "action_group_name": group["name"],
                "openapi_spec": {
                    "openapi": "3.0.0",
                    "info": {
                        "title": f"{group['name']} API",
                        "version": "1.0.0",
                        "description": group["description"]
                    },
                    "paths": {}
                }
            }
            
            # Generate paths for each action
            for action in group["actions"]:
                path = f"/{action['name']}"
                spec["openapi_spec"]["paths"][path] = {
                    "post": {
                        "description": action["description"],
                        "operationId": action["name"],
                        "parameters": [
                            {
                                "name": param["name"],
                                "in": "query",
                                "description": param["description"],
                                "required": param["required"],
                                "schema": {"type": param["type"]}
                            }
                            for param in action["parameters"]
                        ],
                        "responses": {
                            "200": {
                                "description": "Successful response",
                                "content": {
                                    "application/json": {
                                        "schema": {
                                            "type": "object",
                                            "properties": {
                                                "result": {"type": "string"},
                                                "success": {"type": "boolean"}
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            
            api_specs.append(spec)
        
        return api_specs   
 
    def _generate_lambda_implementations(self, action_groups: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Generate Lambda function implementations for action groups."""
        implementations = []
        
        for group in action_groups:
            function_name = group["name"].lower().replace("actions", "_handler")
            
            # Generate handler code
            handler_code = self._generate_handler_code(group)
            
            implementation = {
                "function_name": function_name,
                "description": f"Lambda handler for {group['description']}",
                "runtime": "python3.12",
                "handler": "index.lambda_handler",
                "code": handler_code,
                "requirements": ["boto3", "json", "logging"],
                "environment_variables": {
                    "LOG_LEVEL": "INFO",
                    "ACTION_GROUP": group["name"]
                }
            }
            
            implementations.append(implementation)
        
        return implementations
    
    def _generate_handler_code(self, action_group: Dict[str, Any]) -> str:
        """Generate Lambda handler code for an action group."""
        code = f'''
import json
import boto3
import logging
from typing import Dict, Any

logger = logging.getLogger()
logger.setLevel(logging.INFO)

def lambda_handler(event: Dict[str, Any], context) -> Dict[str, Any]:
    """
    Lambda handler for {action_group["name"]}
    {action_group["description"]}
    """
    try:
        # Extract action details from event
        action_group = event.get("actionGroup", "")
        api_path = event.get("apiPath", "")
        parameters = event.get("parameters", [])
        
        logger.info(f"Processing {{action_group}} action: {{api_path}}")
        
        # Route to appropriate handler based on API path
'''
        
        # Generate routing logic
        for action in action_group["actions"]:
            code += f'''
        if api_path == "/{action['name']}":
            return handle_{action['name']}(parameters)'''
        
        code += '''
        else:
            return {
                "statusCode": 400,
                "body": json.dumps({"error": f"Unknown action path: {api_path}"})
            }
            
    except Exception as e:
        logger.error(f"Error processing request: {str(e)}")
        return {
            "statusCode": 500,
            "body": json.dumps({"error": "Internal server error"})
        }
'''
        
        # Generate handler functions for each action
        for action in action_group["actions"]:
            code += f'''

def handle_{action['name']}(parameters: list) -> Dict[str, Any]:
    """Handle {action['description']}"""
    try:
        # Extract parameters
'''
            for param in action["parameters"]:
                code += f'''
        {param['name']} = get_parameter_value(parameters, "{param['name']}")'''
            
            code += f'''
        
        # TODO: Implement {action['name']} logic here
        # This is a placeholder implementation
        result = f"Executed {action['name']} successfully"
        
        return {{
            "statusCode": 200,
            "body": json.dumps({{
                "result": result,
                "success": True
            }})
        }}
        
    except Exception as e:
        logger.error(f"Error in {action['name']}: {{str(e)}}")
        return {{
            "statusCode": 500,
            "body": json.dumps({{
                "error": f"Failed to execute {action['name']}",
                "success": False
            }})
        }}'''
        
        code += '''

def get_parameter_value(parameters: list, name: str) -> str:
    """Extract parameter value by name."""
    for param in parameters:
        if param.get("name") == name:
            return param.get("value", "")
    return ""
'''
        
        return code.strip() 
   
    def _generate_integrations(self, integration_specs: Dict[str, Any]) -> List[Dict[str, Any]]:
        """Generate integration code based on specifications."""
        integrations = []
        
        for service, spec in integration_specs.items():
            integration = {
                "service": service,
                "type": spec.get("type", "api"),
                "configuration": spec.get("configuration", {}),
                "implementation": self._generate_integration_code(service, spec)
            }
            integrations.append(integration)
        
        return integrations
    
    def _generate_integration_code(self, service: str, spec: Dict[str, Any]) -> str:
        """Generate integration code for a specific service."""
        if spec.get("type") == "api":
            return self._generate_api_integration_code(service, spec)
        elif spec.get("type") == "database":
            return self._generate_database_integration_code(service, spec)
        else:
            return f"# Integration code for {service}\n# TODO: Implement {service} integration"
    
    def _generate_api_integration_code(self, service: str, spec: Dict[str, Any]) -> str:
        """Generate API integration code."""
        return f'''
import requests
import json
from typing import Dict, Any

class {service.title()}Integration:
    """Integration with {service} API"""
    
    def __init__(self, base_url: str, api_key: str = None):
        self.base_url = base_url
        self.api_key = api_key
        self.session = requests.Session()
        
        if api_key:
            self.session.headers.update({{"Authorization": f"Bearer {{api_key}}"}})
    
    def call_api(self, endpoint: str, method: str = "GET", data: Dict[str, Any] = None) -> Dict[str, Any]:
        """Make API call to {service}"""
        url = f"{{self.base_url}}/{{endpoint}}"
        
        try:
            if method.upper() == "GET":
                response = self.session.get(url, params=data)
            elif method.upper() == "POST":
                response = self.session.post(url, json=data)
            elif method.upper() == "PUT":
                response = self.session.put(url, json=data)
            elif method.upper() == "DELETE":
                response = self.session.delete(url)
            else:
                raise ValueError(f"Unsupported HTTP method: {{method}}")
            
            response.raise_for_status()
            return response.json()
            
        except requests.exceptions.RequestException as e:
            raise Exception(f"{service} API call failed: {{str(e)}}")
'''
    
    def _generate_database_integration_code(self, service: str, spec: Dict[str, Any]) -> str:
        """Generate database integration code."""
        return f'''
import boto3
from typing import Dict, Any, List

class {service.title()}Integration:
    """Integration with {service} database"""
    
    def __init__(self, table_name: str, region: str = "us-east-2"):
        self.table_name = table_name
        self.dynamodb = boto3.resource("dynamodb", region_name=region)
        self.table = self.dynamodb.Table(table_name)
    
    def store_item(self, item: Dict[str, Any]) -> bool:
        """Store item in {service}"""
        try:
            self.table.put_item(Item=item)
            return True
        except Exception as e:
            raise Exception(f"Failed to store item in {service}: {{str(e)}}")
    
    def get_item(self, key: Dict[str, Any]) -> Dict[str, Any]:
        """Retrieve item from {service}"""
        try:
            response = self.table.get_item(Key=key)
            return response.get("Item", {{}})
        except Exception as e:
            raise Exception(f"Failed to retrieve item from {service}: {{str(e)}}")
    
    def query_items(self, key_condition: str, **kwargs) -> List[Dict[str, Any]]:
        """Query items from {service}"""
        try:
            response = self.table.query(
                KeyConditionExpression=key_condition,
                **kwargs
            )
            return response.get("Items", [])
        except Exception as e:
            raise Exception(f"Failed to query items from {service}: {{str(e)}}")
'''  
  
    def _generate_deployment_guide(self, action_groups: List[Dict[str, Any]]) -> List[str]:
        """Generate deployment guide for action groups."""
        guide = [
            "# Action Group Deployment Guide",
            "",
            "## Prerequisites",
            "- AWS CLI configured with appropriate permissions",
            "- Python 3.12 runtime environment",
            "- Bedrock Agent created and configured",
            "",
            "## Deployment Steps",
            "",
            "### 1. Deploy Lambda Functions"
        ]
        
        for i, group in enumerate(action_groups, 1):
            function_name = group["name"].lower().replace("actions", "_handler")
            guide.extend([
                f"",
                f"#### {i}.{len([g for g in action_groups[:i] if g == group])} Deploy {group['name']}",
                f"```bash",
                f"# Create deployment package",
                f"zip -r {function_name}.zip index.py",
                f"",
                f"# Deploy Lambda function",
                f"aws lambda create-function \\",
                f"    --function-name agent-{function_name} \\",
                f"    --runtime python3.12 \\",
                f"    --role arn:aws:iam::$ACCOUNT_ID:role/lambda-execution-role \\",
                f"    --handler index.lambda_handler \\",
                f"    --zip-file fileb://{function_name}.zip",
                f"```"
            ])
        
        guide.extend([
            "",
            "### 2. Create Action Groups in Bedrock Agent",
            "```bash",
            "# Create action groups using AWS CLI or Console",
            "aws bedrock-agent create-agent-action-group \\",
            "    --agent-id $AGENT_ID \\",
            "    --agent-version DRAFT \\",
            "    --action-group-name CoreActions \\",
            "    --action-group-executor lambda=$LAMBDA_ARN \\",
            "    --api-schema payload=file://openapi-spec.json",
            "```",
            "",
            "### 3. Test the Agent",
            "```bash",
            "# Test agent functionality",
            "aws bedrock-agent-runtime invoke-agent \\",
            "    --agent-id $AGENT_ID \\",
            "    --agent-alias-id TSTALIASID \\",
            "    --session-id test-session \\",
            "    --input-text \"Test the agent functionality\"",
            "```"
        ])
        
        return guide


class DeploymentTemplateInput(BaseModel):
    """Input schema for deployment template generation tool."""
    agent_config: Dict[str, Any] = Field(description="Complete agent configuration")
    infrastructure_requirements: Optional[Dict[str, Any]] = Field(default=None, description="Infrastructure requirements")


class DeploymentTemplateGeneratorTool(BaseTool):
    """Tool for generating CloudFormation templates for agent deployment."""
    
    name: str = "deployment_template_generator"
    description: str = """Generate CloudFormation templates for complete agent deployment
    including all necessary AWS resources and configurations."""
    
    args_schema: Type[BaseModel] = DeploymentTemplateInput
    
    def _run(self, agent_config: Dict[str, Any], infrastructure_requirements: Optional[Dict[str, Any]] = None) -> str:
        """Generate deployment CloudFormation template."""
        try:
            # Generate complete CloudFormation template
            template = self._generate_complete_template(agent_config, infrastructure_requirements)
            
            # Generate parameter files
            parameter_files = self._generate_parameter_files(agent_config)
            
            # Generate deployment scripts
            deployment_scripts = self._generate_deployment_scripts(agent_config)
            
            result = {
                "cloudformation_template": template,
                "parameter_files": parameter_files,
                "deployment_scripts": deployment_scripts,
                "deployment_instructions": self._generate_deployment_instructions()
            }
            
            return json.dumps(result, indent=2)
            
        except Exception as e:
            return f"Error generating deployment template: {str(e)}"    

    def _generate_complete_template(self, agent_config: Dict[str, Any], infra_reqs: Optional[Dict[str, Any]]) -> Dict[str, Any]:
        """Generate complete CloudFormation template for agent deployment."""
        template = {
            "AWSTemplateFormatVersion": "2010-09-09",
            "Description": f"Complete deployment template for {agent_config.get('agent_name', 'AutoNinja Agent')}",
            "Parameters": self._generate_template_parameters(agent_config),
            "Resources": self._generate_template_resources(agent_config, infra_reqs),
            "Outputs": self._generate_template_outputs(agent_config)
        }
        
        return template
    
    def _generate_template_parameters(self, agent_config: Dict[str, Any]) -> Dict[str, Any]:
        """Generate CloudFormation template parameters."""
        return {
            "AgentName": {
                "Type": "String",
                "Description": "Name of the Bedrock Agent",
                "Default": agent_config.get("agent_name", "AutoNinjaAgent")
            },
            "FoundationModel": {
                "Type": "String",
                "Description": "Foundation model for the agent",
                "Default": agent_config.get("foundation_model", "anthropic.claude-3-sonnet-20240229-v1:0")
            },
            "Environment": {
                "Type": "String",
                "Description": "Deployment environment",
                "Default": "prod",
                "AllowedValues": ["dev", "staging", "prod"]
            }
        }
    
    def _generate_template_resources(self, agent_config: Dict[str, Any], infra_reqs: Optional[Dict[str, Any]]) -> Dict[str, Any]:
        """Generate CloudFormation template resources."""
        resources = {}
        
        # IAM Role for Bedrock Agent
        resources["BedrockAgentRole"] = {
            "Type": "AWS::IAM::Role",
            "Properties": {
                "RoleName": {"Fn::Sub": "${AgentName}-BedrockAgentRole"},
                "AssumeRolePolicyDocument": {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Effect": "Allow",
                            "Principal": {"Service": "bedrock.amazonaws.com"},
                            "Action": "sts:AssumeRole"
                        }
                    ]
                },
                "Policies": [
                    {
                        "PolicyName": "BedrockAgentPolicy",
                        "PolicyDocument": {
                            "Version": "2012-10-17",
                            "Statement": [
                                {
                                    "Effect": "Allow",
                                    "Action": [
                                        "bedrock:InvokeModel",
                                        "bedrock:RetrieveAndGenerate",
                                        "bedrock:Retrieve"
                                    ],
                                    "Resource": "*"
                                },
                                {
                                    "Effect": "Allow",
                                    "Action": ["lambda:InvokeFunction"],
                                    "Resource": {"Fn::Sub": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${AgentName}-*"}
                                }
                            ]
                        }
                    }
                ]
            }
        }
        
        # Lambda execution role
        resources["LambdaExecutionRole"] = {
            "Type": "AWS::IAM::Role",
            "Properties": {
                "RoleName": {"Fn::Sub": "${AgentName}-LambdaExecutionRole"},
                "AssumeRolePolicyDocument": {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Effect": "Allow",
                            "Principal": {"Service": "lambda.amazonaws.com"},
                            "Action": "sts:AssumeRole"
                        }
                    ]
                },
                "ManagedPolicyArns": [
                    "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
                ]
            }
        }
        
        # Add action group Lambda functions
        action_groups = agent_config.get("action_groups", [])
        for i, action_group in enumerate(action_groups):
            function_name = action_group.get("action_group_name", f"ActionGroup{i}")
            
            resources[f"{function_name}Function"] = {
                "Type": "AWS::Lambda::Function",
                "Properties": {
                    "FunctionName": {"Fn::Sub": f"${{AgentName}}-{function_name}"},
                    "Runtime": "python3.12",
                    "Handler": "index.lambda_handler",
                    "Role": {"Fn::GetAtt": ["LambdaExecutionRole", "Arn"]},
                    "Code": {
                        "ZipFile": "# Placeholder Lambda function code\nimport json\ndef lambda_handler(event, context):\n    return {'statusCode': 200, 'body': json.dumps('Hello from Lambda!')}"
                    },
                    "Environment": {
                        "Variables": {
                            "AGENT_NAME": {"Ref": "AgentName"},
                            "ACTION_GROUP": function_name
                        }
                    }
                }
            }
        
        return resources
    
    def _generate_template_outputs(self, agent_config: Dict[str, Any]) -> Dict[str, Any]:
        """Generate CloudFormation template outputs."""
        return {
            "BedrockAgentRoleArn": {
                "Description": "ARN of the Bedrock Agent IAM Role",
                "Value": {"Fn::GetAtt": ["BedrockAgentRole", "Arn"]},
                "Export": {"Name": {"Fn::Sub": "${AWS::StackName}-BedrockAgentRoleArn"}}
            },
            "LambdaExecutionRoleArn": {
                "Description": "ARN of the Lambda Execution Role",
                "Value": {"Fn::GetAtt": ["LambdaExecutionRole", "Arn"]},
                "Export": {"Name": {"Fn::Sub": "${AWS::StackName}-LambdaExecutionRoleArn"}}
            }
        }
    
    def _generate_parameter_files(self, agent_config: Dict[str, Any]) -> Dict[str, Any]:
        """Generate parameter files for different environments."""
        return {
            "dev-parameters.json": [
                {
                    "ParameterKey": "AgentName",
                    "ParameterValue": f"{agent_config.get('agent_name', 'AutoNinjaAgent')}-dev"
                },
                {
                    "ParameterKey": "Environment",
                    "ParameterValue": "dev"
                }
            ],
            "prod-parameters.json": [
                {
                    "ParameterKey": "AgentName",
                    "ParameterValue": agent_config.get('agent_name', 'AutoNinjaAgent')
                },
                {
                    "ParameterKey": "Environment",
                    "ParameterValue": "prod"
                }
            ]
        }
    
    def _generate_deployment_scripts(self, agent_config: Dict[str, Any]) -> Dict[str, str]:
        """Generate deployment scripts."""
        return {
            "deploy.sh": f'''#!/bin/bash
# Deployment script for {agent_config.get('agent_name', 'AutoNinja Agent')}

set -e

STACK_NAME="${{1:-autoninja-agent-stack}}"
ENVIRONMENT="${{2:-prod}}"

echo "Deploying $STACK_NAME in $ENVIRONMENT environment..."

# Deploy CloudFormation stack
aws cloudformation deploy \\
    --template-file template.yaml \\
    --stack-name $STACK_NAME \\
    --parameter-overrides file://${{ENVIRONMENT}}-parameters.json \\
    --capabilities CAPABILITY_NAMED_IAM \\
    --region us-east-2

echo "Deployment completed successfully!"
''',
            "cleanup.sh": '''#!/bin/bash
# Cleanup script

STACK_NAME="${1:-autoninja-agent-stack}"

echo "Cleaning up $STACK_NAME..."

aws cloudformation delete-stack --stack-name $STACK_NAME --region us-east-2

echo "Cleanup initiated. Check AWS Console for status."
'''
        }
    
    def _generate_deployment_instructions(self) -> List[str]:
        """Generate deployment instructions."""
        return [
            "# Deployment Instructions",
            "",
            "## Prerequisites",
            "- AWS CLI configured with appropriate permissions",
            "- CloudFormation permissions for stack creation",
            "- Bedrock service access enabled",
            "",
            "## Deployment Steps",
            "",
            "1. Save the CloudFormation template as 'template.yaml'",
            "2. Save parameter files for each environment",
            "3. Make deployment scripts executable: `chmod +x deploy.sh cleanup.sh`",
            "4. Deploy to development: `./deploy.sh autoninja-agent-dev dev`",
            "5. Deploy to production: `./deploy.sh autoninja-agent-prod prod`",
            "",
            "## Post-Deployment",
            "",
            "1. Create the Bedrock Agent using the AWS Console or CLI",
            "2. Configure action groups with the deployed Lambda functions",
            "3. Test the agent functionality",
            "4. Set up monitoring and alerting"
        ]