default_agent: autoninja_supervisor
agents:
  autoninja_supervisor:
    name: autoninja_supervisor
    entrypoint: /home/mcesel/Documents/proj/autoninja2/lambda/supervisor-agentcore/supervisor_agent.py
    platform: linux/arm64
    container_runtime: docker
    source_path: /home/mcesel/Documents/proj/autoninja2/lambda/supervisor-agentcore
    aws:
      execution_role: arn:aws:iam::784327326356:role/AmazonBedrockAgentCoreSDKRuntime-us-east-2-c6b8f92bf7
      execution_role_auto_create: false
      account: '784327326356'
      region: us-east-2
      ecr_repository: 784327326356.dkr.ecr.us-east-2.amazonaws.com/bedrock-agentcore-autoninja_supervisor
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: autoninja_supervisor-jh9WK8Bgj2
      agent_arn: arn:aws:bedrock-agentcore:us-east-2:784327326356:runtime/autoninja_supervisor-jh9WK8Bgj2
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-autoninja_supervisor-builder
      execution_role: arn:aws:iam::784327326356:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-2-c6b8f92bf7
      source_bucket: bedrock-agentcore-codebuild-sources-784327326356-us-east-2
    memory:
      mode: STM_ONLY
      memory_id: autoninja_supervisor_mem-Fj5viaEP75
      memory_arn: arn:aws:bedrock-agentcore:us-east-2:784327326356:memory/autoninja_supervisor_mem-Fj5viaEP75
      memory_name: autoninja_supervisor_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
