AWSTemplateFormatVersion: "2010-09-09"
Description: >
  AutoNinja Main Stack - Production-grade serverless multi-agent system orchestrator.
  Deploys 1 supervisor + 5 collaborator Bedrock Agents with complete infrastructure.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Environment Configuration
        Parameters:
          - Environment
      - Label:
          default: Bedrock Configuration
        Parameters:
          - BedrockModel
      - Label:
          default: Storage Configuration
        Parameters:
          - DynamoDBBillingMode
          - S3BucketName
      - Label:
          default: Deployment Configuration
        Parameters:
          - DeploymentBucket
      - Label:
          default: Logging Configuration
        Parameters:
          - LogRetentionDays

Parameters:
  Environment:
    Type: String
    Description: Deployment environment
    Default: production
    AllowedValues:
      - production
      - staging
      - development

  BedrockModel:
    Type: String
    Description: Foundation model ID for Bedrock Agents (Supervisor)
    Default: us.anthropic.claude-3-7-sonnet-20250219-v1:0

  RequirementsAnalystModel:
    Type: String
    Description: Foundation model ID for Requirements Analyst
    Default: us.anthropic.claude-3-5-haiku-20241022-v1:0

  CodeGeneratorModel:
    Type: String
    Description: Foundation model ID for Code Generator
    Default: qwen2.5-72b-instruct-v1:0

  SolutionArchitectModel:
    Type: String
    Description: Foundation model ID for Solution Architect
    Default: qwen2.5-14b-instruct-v1:0

  QualityValidatorModel:
    Type: String
    Description: Foundation model ID for Quality Validator
    Default: us.anthropic.claude-3-5-haiku-20241022-v1:0

  DeploymentManagerModel:
    Type: String
    Description: Foundation model ID for Deployment Manager
    Default: deepseek-ai.deepseek-r1-distill-llama-70b-v1:0
    AllowedValues:
      # Global cross-region profiles (highest throughput)
      - us.anthropic.claude-3-7-sonnet-20250219-v1:0
      - global.anthropic.claude-haiku-4-5-20251001-v1:0
      # US cross-region profiles
      - us.anthropic.claude-3-7-sonnet-20250219-v1:0
      - us.anthropic.claude-3-5-sonnet-20241022-v2:0
      - us.anthropic.claude-3-5-haiku-20241022-v1:0
      # Qwen models (good quota)
      - qwen2.5-72b-instruct-v1:0
      - qwen2.5-14b-instruct-v1:0
      - qwen2.5-7b-instruct-v1:0
      # DeepSeek models (good quota)
      - deepseek-ai.deepseek-v3-base
      - deepseek-ai.deepseek-r1-distill-llama-70b-v1:0
      - deepseek-ai.deepseek-r1-distill-qwen-32b-v1:0

  DynamoDBBillingMode:
    Type: String
    Description: Billing mode for DynamoDB tables
    Default: PAY_PER_REQUEST
    AllowedValues:
      - PAY_PER_REQUEST
      - PROVISIONED

  S3BucketName:
    Type: String
    Description: Optional custom name for S3 artifacts bucket
    Default: ""
    AllowedPattern: "^$|^[a-z0-9][a-z0-9-]*[a-z0-9]$"

  DeploymentBucket:
    Type: String
    Description: S3 bucket containing Lambda deployment packages and CloudFormation templates
    Default: ""

  LogRetentionDays:
    Type: Number
    Description: CloudWatch log retention period in days
    Default: 30
    AllowedValues:
      [
        1,
        3,
        5,
        7,
        14,
        30,
        60,
        90,
        120,
        150,
        180,
        365,
        400,
        545,
        731,
        1827,
        3653,
      ]

Conditions:
  UseDefaultDeploymentBucket: !Equals [!Ref DeploymentBucket, ""]

Resources:
  # ============================================================================
  # AgentCore Memory for Rate Limiting (shared across all agents)
  # ============================================================================
  AgentCoreMemory:
    Type: AWS::BedrockAgentCore::Memory
    Properties:
      Name: !Sub "autoninja_rate_limiter_${Environment}"
      EventExpiryDuration: 30
      Description: "AgentCore Memory store for AutoNinja global rate limiting across all agents"
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: AutoNinja
        - Key: Purpose
          Value: RateLimiting

  # ============================================================================
  # Storage Stack - DynamoDB + S3
  # ============================================================================
  StorageStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - "https://${Bucket}.s3.${AWS::Region}.amazonaws.com/stacks/storage.yaml"
        - Bucket: !If
            - UseDefaultDeploymentBucket
            - !Sub "autoninja-deployment-artifacts-${AWS::Region}"
            - !Ref DeploymentBucket
      Parameters:
        Environment: !Ref Environment
        DynamoDBBillingMode: !Ref DynamoDBBillingMode
        S3BucketName: !Ref S3BucketName
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: AutoNinja

  # ============================================================================
  # Lambda Layer Stack - Shared Libraries + Base IAM Policy
  # ============================================================================
  LambdaLayerStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: StorageStack
    Properties:
      TemplateURL: !Sub
        - "https://${Bucket}.s3.${AWS::Region}.amazonaws.com/stacks/lambda-layer.yaml"
        - Bucket: !If
            - UseDefaultDeploymentBucket
            - !Sub "autoninja-deployment-artifacts-${AWS::Region}"
            - !Ref DeploymentBucket
      Parameters:
        Environment: !Ref Environment
        DeploymentBucket: !If
          - UseDefaultDeploymentBucket
          - !Sub "autoninja-deployment-artifacts-${AWS::Region}"
          - !Ref DeploymentBucket
        InferenceRecordsTableArn: !GetAtt StorageStack.Outputs.InferenceRecordsTableArn
        ArtifactsBucketArn: !GetAtt StorageStack.Outputs.ArtifactsBucketArn
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: AutoNinja

  # ============================================================================
  # Custom Orchestration Stack - Rate Limiting Lambda
  # ============================================================================
  CustomOrchestrationStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - "https://${Bucket}.s3.${AWS::Region}.amazonaws.com/stacks/custom-orchestration.yaml"
        - Bucket: !If
            - UseDefaultDeploymentBucket
            - !Sub "autoninja-deployment-artifacts-${AWS::Region}"
            - !Ref DeploymentBucket
      Parameters:
        Environment: !Ref Environment
        DeploymentBucket: !If
          - UseDefaultDeploymentBucket
          - !Sub "autoninja-deployment-artifacts-${AWS::Region}"
          - !Ref DeploymentBucket
        LogRetentionDays: !Ref LogRetentionDays
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: AutoNinja

  # ============================================================================
  # Collaborator Agent Stacks (5 agents)
  # ============================================================================
  RequirementsAnalystStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - StorageStack
      - LambdaLayerStack
      - AgentCoreMemory
    Properties:
      TemplateURL: !Sub
        - "https://${Bucket}.s3.${AWS::Region}.amazonaws.com/stacks/requirements-analyst.yaml"
        - Bucket: !If
            - UseDefaultDeploymentBucket
            - !Sub "autoninja-deployment-artifacts-${AWS::Region}"
            - !Ref DeploymentBucket
      Parameters:
        Environment: !Ref Environment
        DeploymentBucket: !If
          - UseDefaultDeploymentBucket
          - !Sub "autoninja-deployment-artifacts-${AWS::Region}"
          - !Ref DeploymentBucket
        InferenceRecordsTableName: !GetAtt StorageStack.Outputs.InferenceRecordsTableName
        InferenceRecordsTableArn: !GetAtt StorageStack.Outputs.InferenceRecordsTableArn
        ArtifactsBucketName: !GetAtt StorageStack.Outputs.ArtifactsBucketName
        ArtifactsBucketArn: !GetAtt StorageStack.Outputs.ArtifactsBucketArn
        LambdaLayerArn: !GetAtt LambdaLayerStack.Outputs.LayerArn
        LambdaBasePolicyArn: !GetAtt LambdaLayerStack.Outputs.LambdaBasePolicyArn
        LogRetentionDays: !Ref LogRetentionDays
        AgentCoreMemoryId: !GetAtt AgentCoreMemory.MemoryId
        AgentCoreMemoryArn: !GetAtt AgentCoreMemory.MemoryArn
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: AutoNinja

  CodeGeneratorStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - StorageStack
      - LambdaLayerStack
      - AgentCoreMemory
    Properties:
      TemplateURL: !Sub
        - "https://${Bucket}.s3.${AWS::Region}.amazonaws.com/stacks/code-generator.yaml"
        - Bucket: !If
            - UseDefaultDeploymentBucket
            - !Sub "autoninja-deployment-artifacts-${AWS::Region}"
            - !Ref DeploymentBucket
      Parameters:
        Environment: !Ref Environment
        DeploymentBucket: !If
          - UseDefaultDeploymentBucket
          - !Sub "autoninja-deployment-artifacts-${AWS::Region}"
          - !Ref DeploymentBucket
        InferenceRecordsTableName: !GetAtt StorageStack.Outputs.InferenceRecordsTableName
        InferenceRecordsTableArn: !GetAtt StorageStack.Outputs.InferenceRecordsTableArn
        ArtifactsBucketName: !GetAtt StorageStack.Outputs.ArtifactsBucketName
        ArtifactsBucketArn: !GetAtt StorageStack.Outputs.ArtifactsBucketArn
        LambdaLayerArn: !GetAtt LambdaLayerStack.Outputs.LayerArn
        LambdaBasePolicyArn: !GetAtt LambdaLayerStack.Outputs.LambdaBasePolicyArn
        LogRetentionDays: !Ref LogRetentionDays
        AgentCoreMemoryId: !GetAtt AgentCoreMemory.MemoryId
        AgentCoreMemoryArn: !GetAtt AgentCoreMemory.MemoryArn
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: AutoNinja

  SolutionArchitectStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - StorageStack
      - LambdaLayerStack
      - AgentCoreMemory
    Properties:
      TemplateURL: !Sub
        - "https://${Bucket}.s3.${AWS::Region}.amazonaws.com/stacks/solution-architect.yaml"
        - Bucket: !If
            - UseDefaultDeploymentBucket
            - !Sub "autoninja-deployment-artifacts-${AWS::Region}"
            - !Ref DeploymentBucket
      Parameters:
        Environment: !Ref Environment
        DeploymentBucket: !If
          - UseDefaultDeploymentBucket
          - !Sub "autoninja-deployment-artifacts-${AWS::Region}"
          - !Ref DeploymentBucket
        InferenceRecordsTableName: !GetAtt StorageStack.Outputs.InferenceRecordsTableName
        InferenceRecordsTableArn: !GetAtt StorageStack.Outputs.InferenceRecordsTableArn
        ArtifactsBucketName: !GetAtt StorageStack.Outputs.ArtifactsBucketName
        ArtifactsBucketArn: !GetAtt StorageStack.Outputs.ArtifactsBucketArn
        LambdaLayerArn: !GetAtt LambdaLayerStack.Outputs.LayerArn
        LambdaBasePolicyArn: !GetAtt LambdaLayerStack.Outputs.LambdaBasePolicyArn
        LogRetentionDays: !Ref LogRetentionDays
        AgentCoreMemoryId: !GetAtt AgentCoreMemory.MemoryId
        AgentCoreMemoryArn: !GetAtt AgentCoreMemory.MemoryArn
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: AutoNinja

  QualityValidatorStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - StorageStack
      - LambdaLayerStack
      - AgentCoreMemory
    Properties:
      TemplateURL: !Sub
        - "https://${Bucket}.s3.${AWS::Region}.amazonaws.com/stacks/quality-validator.yaml"
        - Bucket: !If
            - UseDefaultDeploymentBucket
            - !Sub "autoninja-deployment-artifacts-${AWS::Region}"
            - !Ref DeploymentBucket
      Parameters:
        Environment: !Ref Environment
        DeploymentBucket: !If
          - UseDefaultDeploymentBucket
          - !Sub "autoninja-deployment-artifacts-${AWS::Region}"
          - !Ref DeploymentBucket
        InferenceRecordsTableName: !GetAtt StorageStack.Outputs.InferenceRecordsTableName
        InferenceRecordsTableArn: !GetAtt StorageStack.Outputs.InferenceRecordsTableArn
        ArtifactsBucketName: !GetAtt StorageStack.Outputs.ArtifactsBucketName
        ArtifactsBucketArn: !GetAtt StorageStack.Outputs.ArtifactsBucketArn
        LambdaLayerArn: !GetAtt LambdaLayerStack.Outputs.LayerArn
        LambdaBasePolicyArn: !GetAtt LambdaLayerStack.Outputs.LambdaBasePolicyArn
        LogRetentionDays: !Ref LogRetentionDays
        AgentCoreMemoryId: !GetAtt AgentCoreMemory.MemoryId
        AgentCoreMemoryArn: !GetAtt AgentCoreMemory.MemoryArn
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: AutoNinja

  DeploymentManagerStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - StorageStack
      - LambdaLayerStack
      - AgentCoreMemory
    Properties:
      TemplateURL: !Sub
        - "https://${Bucket}.s3.${AWS::Region}.amazonaws.com/stacks/deployment-manager.yaml"
        - Bucket: !If
            - UseDefaultDeploymentBucket
            - !Sub "autoninja-deployment-artifacts-${AWS::Region}"
            - !Ref DeploymentBucket
      Parameters:
        Environment: !Ref Environment
        DeploymentBucket: !If
          - UseDefaultDeploymentBucket
          - !Sub "autoninja-deployment-artifacts-${AWS::Region}"
          - !Ref DeploymentBucket
        InferenceRecordsTableName: !GetAtt StorageStack.Outputs.InferenceRecordsTableName
        InferenceRecordsTableArn: !GetAtt StorageStack.Outputs.InferenceRecordsTableArn
        ArtifactsBucketName: !GetAtt StorageStack.Outputs.ArtifactsBucketName
        ArtifactsBucketArn: !GetAtt StorageStack.Outputs.ArtifactsBucketArn
        LambdaLayerArn: !GetAtt LambdaLayerStack.Outputs.LayerArn
        LambdaBasePolicyArn: !GetAtt LambdaLayerStack.Outputs.LambdaBasePolicyArn
        LogRetentionDays: !Ref LogRetentionDays
        AgentCoreMemoryId: !GetAtt AgentCoreMemory.MemoryId
        AgentCoreMemoryArn: !GetAtt AgentCoreMemory.MemoryArn
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: AutoNinja

  # ============================================================================
  # Supervisor Agent Stack
  # ============================================================================
  SupervisorStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - RequirementsAnalystStack
      - CodeGeneratorStack
      - SolutionArchitectStack
      - QualityValidatorStack
      - DeploymentManagerStack
      - AgentCoreMemory
    Properties:
      TemplateURL: !Sub
        - "https://${Bucket}.s3.${AWS::Region}.amazonaws.com/stacks/supervisor.yaml"
        - Bucket: !If
            - UseDefaultDeploymentBucket
            - !Sub "autoninja-deployment-artifacts-${AWS::Region}"
            - !Ref DeploymentBucket
      Parameters:
        Environment: !Ref Environment

        ArtifactsBucketName: !GetAtt StorageStack.Outputs.ArtifactsBucketName
        InferenceRecordsTableName: !GetAtt StorageStack.Outputs.InferenceRecordsTableName
        InferenceRecordsTableArn: !GetAtt StorageStack.Outputs.InferenceRecordsTableArn
        ArtifactsBucketArn: !GetAtt StorageStack.Outputs.ArtifactsBucketArn
        DeploymentBucket: !If
          - UseDefaultDeploymentBucket
          - !Sub "autoninja-deployment-artifacts-${AWS::Region}"
          - !Ref DeploymentBucket
        LogRetentionDays: !Ref LogRetentionDays
        AgentCoreMemoryId: !GetAtt AgentCoreMemory.MemoryId
        AgentCoreMemoryArn: !GetAtt AgentCoreMemory.MemoryArn
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: AutoNinja

Outputs:
  # Supervisor Agent Outputs
  SupervisorAgentId:
    Description: Supervisor Agent ID
    Value: !GetAtt SupervisorStack.Outputs.AgentId
    Export:
      Name: !Sub "${AWS::StackName}-SupervisorAgentId"

  SupervisorAgentAliasId:
    Description: Supervisor Agent Alias ID
    Value: !GetAtt SupervisorStack.Outputs.AgentAliasId
    Export:
      Name: !Sub "${AWS::StackName}-SupervisorAgentAliasId"

  # Collaborator Agent IDs
  RequirementsAnalystAgentId:
    Description: Requirements Analyst Agent ID
    Value: !GetAtt RequirementsAnalystStack.Outputs.AgentId

  CodeGeneratorAgentId:
    Description: Code Generator Agent ID
    Value: !GetAtt CodeGeneratorStack.Outputs.AgentId

  SolutionArchitectAgentId:
    Description: Solution Architect Agent ID
    Value: !GetAtt SolutionArchitectStack.Outputs.AgentId

  QualityValidatorAgentId:
    Description: Quality Validator Agent ID
    Value: !GetAtt QualityValidatorStack.Outputs.AgentId

  DeploymentManagerAgentId:
    Description: Deployment Manager Agent ID
    Value: !GetAtt DeploymentManagerStack.Outputs.AgentId

  # Storage Outputs
  InferenceRecordsTableName:
    Description: DynamoDB inference records table name
    Value: !GetAtt StorageStack.Outputs.InferenceRecordsTableName

  ArtifactsBucketName:
    Description: S3 artifacts bucket name
    Value: !GetAtt StorageStack.Outputs.ArtifactsBucketName

  # Invocation Command
  SupervisorInvocationCommand:
    Description: Command to invoke the supervisor agent
    Value: !GetAtt SupervisorStack.Outputs.InvocationCommand

  # AgentCore Memory (shared)
  AgentCoreMemoryId:
    Description: AgentCore Memory ID for rate limiting
    Value: !GetAtt AgentCoreMemory.MemoryId
    Export:
      Name: !Sub "${AWS::StackName}-AgentCoreMemoryId"

  AgentCoreMemoryArn:
    Description: AgentCore Memory ARN for rate limiting
    Value: !GetAtt AgentCoreMemory.MemoryArn
    Export:
      Name: !Sub "${AWS::StackName}-AgentCoreMemoryArn"

  # Environment
  Environment:
    Description: Deployment environment
    Value: !Ref Environment
