# ============================================================================
# Custom Orchestration Lambda Function and Role
# Add these resources AFTER the Deployment Manager Lambda Function (around line 660)
# and BEFORE the Lambda Permissions section (around line 662)
# ============================================================================

  # Custom Orchestration Lambda Role
  CustomOrchestrationLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "AutoNinjaCustomOrchestrationRole-${Environment}"
      Description: Execution role for Custom Orchestration Lambda function
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: BedrockConverseAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: InvokeBedrockModels
                Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:Converse
                  - bedrock:ConverseStream
                Resource:
                  - !Sub "arn:aws:bedrock:*::foundation-model/*"
                  - !Sub "arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:inference-profile/*"
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: AutoNinja

  # Custom Orchestration Lambda Function
  CustomOrchestrationFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "autoninja-custom-orchestration-${Environment}"
      Description: Custom orchestration handler for Bedrock Agents - enforces sequential tool execution with rate limiting
      Runtime: python3.12
      Handler: handler.lambda_handler
      Role: !GetAtt CustomOrchestrationLambdaRole.Arn
      Timeout: 600
      MemorySize: 512
      Architectures:
        - x86_64
      Environment:
        Variables:
          MIN_INTERVAL_SECONDS: "60"
          LOG_LEVEL: INFO
          ENVIRONMENT: !Ref Environment
      TracingConfig:
        Mode: Active
      Code:
        S3Bucket: !Sub "autoninja-deployment-artifacts-${AWS::Region}"
        S3Key: lambda/custom-orchestration.zip
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: AutoNinja

  # Lambda Permission for Custom Orchestration (Allow Bedrock Agents to Invoke)
  CustomOrchestrationInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CustomOrchestrationFunction
      Action: lambda:InvokeFunction
      Principal: bedrock.amazonaws.com
      SourceAccount: !Ref AWS::AccountId

  # CloudWatch Log Group for Custom Orchestration
  CustomOrchestrationLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/autoninja-custom-orchestration-${Environment}"
      RetentionInDays: !Ref LogRetentionDays
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: AutoNinja

# ============================================================================
# Update ALL 5 Bedrock Agent Resources (NOT Supervisor)
# Add these two properties to EACH of the 5 sub-agent definitions:
#   - RequirementsAnalystAgent (line ~1036)
#   - CodeGeneratorAgent (line ~1079)
#   - SolutionArchitectAgent (line ~1120)
#   - QualityValidatorAgent (line ~1163)
#   - DeploymentManagerAgent (line ~1205)
#
# Add AFTER the "AutoPrepare: true" line and BEFORE the "Instruction:" line:
# ============================================================================

      OrchestrationType: CUSTOM_ORCHESTRATION
      CustomOrchestrationConfiguration:
        Executor:
          Lambda: !GetAtt CustomOrchestrationFunction.Arn

# ============================================================================
# Example of what the updated agent should look like:
# ============================================================================

  # Requirements Analyst Bedrock Agent (EXAMPLE - DO NOT COPY, MODIFY EXISTING)
  RequirementsAnalystAgent:
    Type: AWS::Bedrock::Agent
    DependsOn:
      - RequirementsAnalystFunction
      - RequirementsAnalystAgentRole
      - DeploymentArtifactsBucketPolicy
      - CustomOrchestrationFunction  # ADD THIS DEPENDENCY
    Properties:
      AgentName: !Sub "autoninja-requirements-analyst-${Environment}"
      Description: Requirements Analyst agent - extracts and validates requirements from user requests
      AgentResourceRoleArn: !GetAtt RequirementsAnalystAgentRole.Arn
      FoundationModel: !Ref BedrockModel
      AgentCollaboration: DISABLED
      IdleSessionTTLInSeconds: 1800
      AutoPrepare: true
      OrchestrationType: CUSTOM_ORCHESTRATION  # ADD THIS LINE
      CustomOrchestrationConfiguration:         # ADD THIS BLOCK
        Executor:
          Lambda: !GetAtt CustomOrchestrationFunction.Arn
      Instruction: |
        You are a requirements analyst for the AutoNinja system...
        # (rest of instruction unchanged)
      ActionGroups:
        # (unchanged)
      Tags:
        # (unchanged)
