AWSTemplateFormatVersion: '2010-09-09'
Description: 'AutoNinja Frontend Infrastructure - AWS Amplify Hosting for React Dashboard'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'Environment Configuration'
        Parameters:
          - Environment
          - BranchName
      - Label:
          default: 'Security Configuration'
        Parameters:
          - DashboardPassword
    ParameterLabels:
      Environment:
        default: 'Deployment Environment'
      BranchName:
        default: 'Git Branch Name'
      DashboardPassword:
        default: 'Dashboard Access Password'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - production
      - staging
      - development
    Description: 'Deployment environment for the frontend application'

  BranchName:
    Type: String
    Default: main
    Description: 'Git branch name for deployment'

  DashboardPassword:
    Type: String
    NoEcho: true
    MinLength: 12
    Description: 'Password for dashboard authentication (minimum 12 characters)'

Resources:
  # IAM Role for Amplify Service
  AmplifyServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'autoninja-amplify-service-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: amplify.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess-Amplify
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: AutoNinja
        - Key: ManagedBy
          Value: CloudFormation

  # Amplify App Resource
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: !Sub 'autoninja-frontend-${Environment}'
      Description: 'AutoNinja React Dashboard with password authentication'
      Repository: ''
      IAMServiceRole: !GetAtt AmplifyServiceRole.Arn
      Platform: WEB
      EnvironmentVariables:
        - Name: REACT_APP_DASHBOARD_PASSWORD
          Value: !Ref DashboardPassword
        - Name: REACT_APP_ENVIRONMENT
          Value: !Ref Environment
        - Name: NODE_ENV
          Value: production
      BuildSpec: |
        version: 1
        frontend:
          phases:
            preBuild:
              commands:
                - cd frontend
                - npm ci
            build:
              commands:
                - npm run build
          artifacts:
            baseDirectory: frontend/build
            files:
              - '**/*'
          cache:
            paths:
              - frontend/node_modules/**/*
      CustomRules:
        - Source: '</^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|woff2|ttf|map|json)$)([^.]+$)/>'
          Target: '/index.html'
          Status: '200'
        - Source: '/<*>'
          Target: '/index.html'
          Status: '404-200'
      CustomHeaders: |
        customHeaders:
          - pattern: '**/*'
            headers:
              - key: 'Strict-Transport-Security'
                value: 'max-age=31536000; includeSubDomains'
              - key: 'X-Frame-Options'
                value: 'SAMEORIGIN'
              - key: 'X-Content-Type-Options'
                value: 'nosniff'
              - key: 'X-XSS-Protection'
                value: '1; mode=block'
              - key: 'Referrer-Policy'
                value: 'strict-origin-when-cross-origin'
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: AutoNinja
        - Key: ManagedBy
          Value: CloudFormation

  # Amplify Branch Resource
  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !GetAtt AmplifyApp.AppId
      BranchName: !Ref BranchName
      EnableAutoBuild: false
      EnablePullRequestPreview: false
      Stage: PRODUCTION
      EnvironmentVariables:
        - Name: REACT_APP_BRANCH
          Value: !Ref BranchName
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Application
          Value: AutoNinja

Outputs:
  AmplifyAppId:
    Description: 'Amplify App ID'
    Value: !GetAtt AmplifyApp.AppId
    Export:
      Name: !Sub '${AWS::StackName}-AmplifyAppId'

  AmplifyAppUrl:
    Description: 'Amplify App URL for accessing the frontend'
    Value: !Sub 'https://${BranchName}.${AmplifyApp.DefaultDomain}'
    Export:
      Name: !Sub '${AWS::StackName}-AmplifyAppUrl'

  AmplifyBranchName:
    Description: 'Amplify Branch Name'
    Value: !Ref BranchName
    Export:
      Name: !Sub '${AWS::StackName}-AmplifyBranchName'

  AmplifyDefaultDomain:
    Description: 'Amplify Default Domain'
    Value: !GetAtt AmplifyApp.DefaultDomain
    Export:
      Name: !Sub '${AWS::StackName}-AmplifyDefaultDomain'

  AmplifyServiceRoleArn:
    Description: 'IAM Role ARN for Amplify Service'
    Value: !GetAtt AmplifyServiceRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-AmplifyServiceRoleArn'
