openapi: 3.0.0
info:
  title: Code Generator API
  version: 1.0.0
  description: Comprehensive code generation for AI agents

paths:
  /generate:
    post:
      summary: Comprehensive Code Generation
      description: Generates complete Lambda code, agent configuration, and OpenAPI schema
      operationId: generateCode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - job_name
                - requirements
                - architecture
              properties:
                job_name:
                  type: string
                  description: Unique job identifier
                requirements:
                  type: string
                  description: JSON string of requirements from Requirements Analyst
                architecture:
                  type: string
                  description: JSON string of architecture from Solution Architect
      responses:
        '200':
          description: Comprehensive code generation completed
          content:
            application/json:
              schema:
                type: object
                required:
                  - job_name
                  - code
                  - status
                properties:
                  job_name:
                    type: string
                  code:
                    type: object
                    description: Complete code package
                    properties:
                      lambda_code:
                        type: object
                        description: Lambda function code and dependencies
                      agent_config:
                        type: object
                        description: Bedrock Agent configuration
                      openapi_schema:
                        type: object
                        description: OpenAPI schema for agent actions
                      documentation:
                        type: object
                        description: Code documentation and usage guides
                  status:
                    type: string
                    enum: [success, error]
