openapi: 3.0.0
info:
  title: Code Generator Action Group API
  description: API for generating Lambda code, agent configurations, and OpenAPI schemas
  version: 1.0.0

paths:
  /generate-lambda-code:
    post:
      summary: Generate Lambda function code
      description: Generates production-ready Python Lambda function code with error handling, logging, and persistence
      operationId: generateLambdaCode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - job_name
                - requirements
              properties:
                job_name:
                  type: string
                  description: Unique job identifier in format job-{keyword}-{YYYYMMDD-HHMMSS}
                requirements:
                  type: string
                  description: JSON string containing requirements from Requirements Analyst
                function_spec:
                  type: string
                  description: JSON string containing specific function specifications
      responses:
        '200':
          description: Lambda code successfully generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_name:
                    type: string
                    description: Job identifier
                  lambda_code:
                    type: string
                    description: JSON string containing map of filename to code content
                  requirements_txt:
                    type: string
                    description: Python dependencies file content
                  status:
                    type: string
                    description: Status of operation
        '400':
          description: Invalid request
        '500':
          description: Internal server error

  /generate-agent-config:
    post:
      summary: Generate Bedrock Agent configuration
      description: Creates Bedrock Agent configuration JSON with agent name, instructions, foundation model, and action groups
      operationId: generateAgentConfig
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - job_name
                - requirements
              properties:
                job_name:
                  type: string
                  description: Unique job identifier
                requirements:
                  type: string
                  description: JSON string containing requirements from Requirements Analyst
      responses:
        '200':
          description: Agent configuration successfully generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_name:
                    type: string
                    description: Job identifier
                  agent_config:
                    type: string
                    description: JSON string containing agent configuration
                  status:
                    type: string
                    description: Status of operation
        '400':
          description: Invalid request
        '500':
          description: Internal server error

  /generate-openapi-schema:
    post:
      summary: Generate OpenAPI schema for action groups
      description: Creates OpenAPI 3.0 schema defining all endpoints, parameters, and request/response formats
      operationId: generateOpenapiSchema
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - job_name
                - action_group_spec
              properties:
                job_name:
                  type: string
                  description: Unique job identifier
                action_group_spec:
                  type: string
                  description: JSON string containing specification for the action group
      responses:
        '200':
          description: OpenAPI schema successfully generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_name:
                    type: string
                    description: Job identifier
                  openapi_schema:
                    type: string
                    description: OpenAPI 3.0 schema in YAML format
                  status:
                    type: string
                    description: Status of operation
        '400':
          description: Invalid request
        '500':
          description: Internal server error
