openapi: 3.0.0
info:
  title: Deployment Manager API
  version: 1.0.0
  description: Deploy Bedrock Agents to AWS

paths:
  /deploy:
    post:
      summary: Deploy Bedrock Agent
      description: Package code, upload to S3, generate CloudFormation, and deploy to AWS
      operationId: deployAgent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - job_name
                - code
              properties:
                job_name:
                  type: string
                  description: Unique job identifier
                code:
                  type: string
                  description: JSON string containing lambda_code, agent_config, and openapi_schema from Code Generator
      responses:
        '200':
          description: Deployment completed
          content:
            application/json:
              schema:
                type: object
                required:
                  - job_name
                  - status
                properties:
                  job_name:
                    type: string
                  stack_name:
                    type: string
                    description: CloudFormation stack name
                  stack_id:
                    type: string
                    description: CloudFormation stack ID
                  stack_status:
                    type: string
                    description: Stack deployment status
                  agent_id:
                    type: string
                    description: Deployed Bedrock Agent ID
                  agent_alias_id:
                    type: string
                    description: Production alias ID
                  lambda_arn:
                    type: string
                    description: Deployed Lambda function ARN
                  s3_locations:
                    type: object
                    description: S3 locations of uploaded artifacts
                    properties:
                      lambda_code:
                        type: string
                      schema:
                        type: string
                  status:
                    type: string
                    enum: [success, error]
                  error:
                    type: string
                    description: Error message if deployment failed
