openapi: 3.0.0
info:
  title: Quality Validator API
  version: 1.0.0
  description: Universal quality validation for requirements, architecture, and code

paths:
  /validate:
    post:
      summary: Universal Quality Validation
      description: Validates requirements, architecture, or code based on type parameter
      operationId: validateQuality
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - job_name
                - type
                - data
              properties:
                job_name:
                  type: string
                  description: Unique job identifier
                type:
                  type: string
                  enum: [requirements, architecture, code]
                  description: Type of validation to perform
                data:
                  type: string
                  description: JSON string of data to validate
                requirements:
                  type: string
                  description: JSON string of requirements (for architecture/code validation)
                architecture:
                  type: string
                  description: JSON string of architecture (for code validation)
      responses:
        '200':
          description: Quality validation completed
          content:
            application/json:
              schema:
                type: object
                required:
                  - job_name
                  - validation_type
                  - is_valid
                  - status
                properties:
                  job_name:
                    type: string
                  validation_type:
                    type: string
                    enum: [requirements, architecture, code]
                  is_valid:
                    type: boolean
                    description: Whether the validation passed
                  score:
                    type: number
                    description: Quality score (0-100)
                  issues:
                    type: array
                    items:
                      type: object
                      properties:
                        severity:
                          type: string
                          enum: [low, medium, high, critical]
                        category:
                          type: string
                        description:
                          type: string
                        recommendation:
                          type: string
                  recommendations:
                    type: array
                    items:
                      type: string
                    description: Improvement suggestions
                  status:
                    type: string
                    enum: [success, error]
