openapi: 3.0.0
info:
  title: Quality Validator Action Group API
  description: API for validating code quality, performing security scans, and checking compliance
  version: 1.0.0

paths:
  /validate-code:
    post:
      summary: Validate code quality
      description: Performs comprehensive code quality validation including syntax, error handling, logging, and structure checks
      operationId: validateCode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - job_name
                - code
              properties:
                job_name:
                  type: string
                  description: Unique job identifier in format job-{keyword}-{YYYYMMDD-HHMMSS}
                code:
                  type: string
                  description: JSON string containing code artifacts to validate
                language:
                  type: string
                  description: Programming language (default python)
      responses:
        '200':
          description: Code validation completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_name:
                    type: string
                    description: Job identifier
                  is_valid:
                    type: boolean
                    description: Whether code passes validation
                  issues:
                    type: string
                    description: JSON string containing list of code quality issues found
                  quality_score:
                    type: number
                    description: Overall quality score (0-100)
                  status:
                    type: string
                    description: Status of operation
        '400':
          description: Invalid request
        '500':
          description: Internal server error

  /security-scan:
    post:
      summary: Perform security scanning
      description: Scans code for security vulnerabilities including hardcoded credentials, injection risks, and improper IAM permissions
      operationId: securityScan
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - job_name
                - code
              properties:
                job_name:
                  type: string
                  description: Unique job identifier
                code:
                  type: string
                  description: JSON string containing code artifacts to scan
                iam_policies:
                  type: string
                  description: JSON string containing IAM policies to validate
      responses:
        '200':
          description: Security scan completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_name:
                    type: string
                    description: Job identifier
                  vulnerabilities:
                    type: string
                    description: JSON string containing list of security vulnerabilities found
                  risk_level:
                    type: string
                    description: Overall risk assessment (low, medium, high)
                  status:
                    type: string
                    description: Status of operation
        '400':
          description: Invalid request
        '500':
          description: Internal server error

  /compliance-check:
    post:
      summary: Check compliance with standards
      description: Validates compliance with AWS best practices, Lambda best practices, and Python PEP 8 standards
      operationId: complianceCheck
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - job_name
                - code
              properties:
                job_name:
                  type: string
                  description: Unique job identifier
                code:
                  type: string
                  description: JSON string containing code artifacts to check
                architecture:
                  type: string
                  description: JSON string containing architecture design to validate
      responses:
        '200':
          description: Compliance check completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_name:
                    type: string
                    description: Job identifier
                  compliant:
                    type: boolean
                    description: Whether code meets compliance standards
                  violations:
                    type: string
                    description: JSON string containing list of compliance violations found
                  status:
                    type: string
                    description: Status of operation
        '400':
          description: Invalid request
        '500':
          description: Internal server error
