openapi: 3.0.0
info:
  title: Requirements Analyst Action Group API
  description: API for extracting, analyzing, and validating requirements from user
    requests
  version: 1.0.0
paths:
  /extract-requirements:
    post:
      summary: Extract structured requirements from user request
      description: Analyzes user request and extracts comprehensive requirements for
        all sub-agents (Code Generator, Solution Architect, Quality Validator, Deployment
        Manager)
      operationId: extractRequirements
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - job_name
              - user_request
              properties:
                job_name:
                  type: string
                  description: Unique job identifier in format job-{keyword}-{YYYYMMDD-HHMMSS}
                  example: job-friend-20251013-143022
                user_request:
                  type: string
                  description: Natural language description of the desired agent
                  example: I would like a friend agent that can have conversations
      responses:
        '200':
          description: Requirements successfully extracted
          content:
            application/json:
              schema:
                type: object
                required:
                - job_name
                - requirements
                - status
                properties:
                  job_name:
                    type: string
                  requirements:
                    type: object
                    properties:
                      agent_purpose:
                        type: string
                      capabilities:
                        type: array
                        items:
                          type: string
                      interactions:
                        type: array
                        items:
                          type: string
                      data_needs:
                        type: array
                        items:
                          type: string
                      integrations:
                        type: array
                        items:
                          type: string
                      system_prompts:
                        type: string
                      lambda_requirements:
                        type: object
                      architecture_requirements:
                        type: object
                      deployment_requirements:
                        type: object
                      complexity:
                        type: string
                      additional_notes:
                        type: string
                  status:
                    type: string
        '400':
          description: Invalid request
        '500':
          description: Internal server error
  /analyze-complexity:
    post:
      summary: Analyze complexity of requirements
      description: Assesses the complexity of extracted requirements and provides
        complexity score
      operationId: analyzeComplexity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - job_name
              - requirements
              properties:
                job_name:
                  type: string
                  description: Unique job identifier
                  example: job-friend-20251013-143022
                requirements:
                  type: object
                  description: Previously extracted requirements
      responses:
        '200':
          description: Complexity analysis completed
          content:
            application/json:
              schema:
                type: object
                required:
                - job_name
                - complexity_score
                - assessment
                properties:
                  job_name:
                    type: string
                  complexity_score:
                    type: string
                  assessment:
                    type: object
                    properties:
                      estimated_effort:
                        type: string
                      key_challenges:
                        type: array
                        items:
                          type: string
                      recommended_approach:
                        type: string
        '400':
          description: Invalid request
        '500':
          description: Internal server error
  /validate-requirements:
    post:
      summary: Validate completeness of requirements
      description: Checks requirements for completeness and identifies missing information
      operationId: validateRequirements
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - job_name
              - requirements
              properties:
                job_name:
                  type: string
                  description: Unique job identifier
                  example: job-friend-20251013-143022
                requirements:
                  type: object
                  description: Requirements to validate
      responses:
        '200':
          description: Validation completed
          content:
            application/json:
              schema:
                type: object
                required:
                - job_name
                - is_valid
                - missing_items
                properties:
                  job_name:
                    type: string
                  is_valid:
                    type: boolean
                  missing_items:
                    type: array
                    items:
                      type: string
                  recommendations:
                    type: array
                    items:
                      type: string
        '400':
          description: Invalid request
        '500':
          description: Internal server error
