openapi: 3.0.0
info:
  title: Requirements Analyst API
  version: 1.0.0
  description: Comprehensive requirements analysis for AI agent generation

paths:
  /analyze:
    post:
      summary: Comprehensive Requirements Analysis
      description: Analyzes user request and generates complete structured requirements with complexity assessment
      operationId: analyzeRequirements
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - job_name
                - user_request
              properties:
                job_name:
                  type: string
                  description: Unique job identifier
                user_request:
                  type: string
                  description: Natural language description of the desired AI agent
      responses:
        '200':
          description: Comprehensive requirements analysis completed
          content:
            application/json:
              schema:
                type: object
                required:
                  - job_name
                  - requirements
                  - status
                properties:
                  job_name:
                    type: string
                  requirements:
                    type: object
                    description: Customer-focused structured requirements
                    properties:
                      executive_summary:
                        type: object
                        properties:
                          agent_name:
                            type: string
                          purpose:
                            type: string
                          business_value:
                            type: string
                          complexity_level:
                            type: string
                            enum: [low, medium, high]
                          estimated_effort:
                            type: string
                      for_solution_architect:
                        type: object
                        description: Architecture requirements
                      for_code_generator:
                        type: object
                        description: Code generation requirements
                      for_quality_validator:
                        type: object
                        description: Quality and compliance requirements
                      for_deployment_manager:
                        type: object
                        description: Infrastructure and deployment requirements
                      validation_criteria:
                        type: object
                        description: Success metrics and acceptance criteria
                  status:
                    type: string
                    enum: [success, error]
