openapi: 3.0.0
info:
  title: Requirements Analyst Action Group API
  description: API for extracting, analyzing, and validating requirements from user requests
  version: 1.0.0

paths:
  /extract-requirements:
    post:
      summary: Extract structured requirements from user request
      description: Analyzes user request and extracts comprehensive requirements for all sub-agents
      operationId: extractRequirements
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - job_name
                - user_request
              properties:
                job_name:
                  type: string
                  description: Unique job identifier in format job-{keyword}-{YYYYMMDD-HHMMSS}
                user_request:
                  type: string
                  description: Natural language description of the desired agent
      responses:
        '200':
          description: Requirements successfully extracted
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_name:
                    type: string
                    description: Job identifier
                  requirements:
                    type: string
                    description: JSON string containing structured requirements object
                  status:
                    type: string
                    description: Status of operation
        '400':
          description: Invalid request
        '500':
          description: Internal server error

  /analyze-complexity:
    post:
      summary: Analyze complexity of requirements
      description: Assesses the complexity of extracted requirements and provides complexity score
      operationId: analyzeComplexity
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - job_name
                - requirements
              properties:
                job_name:
                  type: string
                  description: Unique job identifier
                requirements:
                  type: string
                  description: JSON string containing previously extracted requirements
      responses:
        '200':
          description: Complexity analysis completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_name:
                    type: string
                    description: Job identifier
                  complexity_score:
                    type: string
                    description: Complexity score (low, medium, high)
                  assessment:
                    type: string
                    description: JSON string containing detailed complexity assessment
                  status:
                    type: string
                    description: Status of operation
        '400':
          description: Invalid request
        '500':
          description: Internal server error

  /validate-requirements:
    post:
      summary: Validate completeness of requirements
      description: Checks requirements for completeness and identifies missing information
      operationId: validateRequirements
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - job_name
                - requirements
              properties:
                job_name:
                  type: string
                  description: Unique job identifier
                requirements:
                  type: string
                  description: JSON string containing requirements to validate
      responses:
        '200':
          description: Validation completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_name:
                    type: string
                    description: Job identifier
                  is_valid:
                    type: boolean
                    description: Whether requirements are complete
                  missing_items:
                    type: array
                    items:
                      type: string
                    description: List of missing requirement items
                  recommendations:
                    type: array
                    items:
                      type: string
                    description: Recommendations for improvement
                  status:
                    type: string
                    description: Status of operation
        '400':
          description: Invalid request
        '500':
          description: Internal server error
