openapi: 3.0.0
info:
  title: Solution Architect Action Group API
  description: API for designing AWS architecture, selecting services, and generating
    infrastructure-as-code
  version: 1.0.0
paths:
  /design-architecture:
    post:
      summary: Design complete AWS architecture
      description: Creates comprehensive AWS architecture design based on requirements
        and code files from Code Generator
      operationId: designArchitecture
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - job_name
              - requirements
              properties:
                job_name:
                  type: string
                  description: Unique job identifier in format job-{keyword}-{YYYYMMDD-HHMMSS}
                  example: job-friend-20251013-143022
                requirements:
                  type: object
                  description: Requirements from Requirements Analyst
                code_file_references:
                  type: object
                  description: References to code files generated by Code Generator
      responses:
        '200':
          description: Architecture successfully designed
          content:
            application/json:
              schema:
                type: object
                required:
                - job_name
                - architecture
                - status
                properties:
                  job_name:
                    type: string
                  architecture:
                    type: object
                    properties:
                      services:
                        type: array
                        items:
                          type: string
                      resources:
                        type: object
                      iam_policies:
                        type: object
                      integration_points:
                        type: array
                        items:
                          type: object
                      architecture_diagram:
                        type: string
                      service_rationale:
                        type: object
                      cost_estimate:
                        type: string
                      scalability_notes:
                        type: string
                  diagram:
                    type: string
                    description: Architecture diagram in text or Mermaid format
                  status:
                    type: string
        '400':
          description: Invalid request
        '500':
          description: Internal server error
  /select-services:
    post:
      summary: Select appropriate AWS services
      description: Analyzes requirements and selects optimal AWS services with rationale
      operationId: selectServices
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - job_name
              - requirements
              properties:
                job_name:
                  type: string
                  description: Unique job identifier
                  example: job-friend-20251013-143022
                requirements:
                  type: object
                  description: Requirements from Requirements Analyst
      responses:
        '200':
          description: Services successfully selected
          content:
            application/json:
              schema:
                type: object
                required:
                - job_name
                - services
                - rationale
                properties:
                  job_name:
                    type: string
                  services:
                    type: array
                    items:
                      type: string
                    description: List of selected AWS services
                  rationale:
                    type: string
                    description: JSON string containing justification for each service
                      selection
        '400':
          description: Invalid request
        '500':
          description: Internal server error
  /generate-iac:
    post:
      summary: Generate infrastructure-as-code templates
      description: Creates CloudFormation/Terraform templates that reference Lambda
        code files and include all architecture components
      operationId: generateIac
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - job_name
              - architecture
              properties:
                job_name:
                  type: string
                  description: Unique job identifier
                  example: job-friend-20251013-143022
                architecture:
                  type: object
                  description: Architecture design from design_architecture action
                code_references:
                  type: object
                  description: References to Lambda code and agent config files
      responses:
        '200':
          description: IaC templates successfully generated
          content:
            application/json:
              schema:
                type: object
                required:
                - job_name
                - cloudformation_template
                - status
                properties:
                  job_name:
                    type: string
                  cloudformation_template:
                    type: string
                    description: CloudFormation template in YAML format
                  terraform_module:
                    type: string
                    description: Terraform module (optional)
                  status:
                    type: string
        '400':
          description: Invalid request
        '500':
          description: Internal server error
