openapi: 3.0.0
info:
  title: Solution Architect API
  version: 1.0.0
  description: Comprehensive AWS architecture design for AI agents

paths:
  /design:
    post:
      summary: Comprehensive Architecture Design
      description: Designs complete AWS architecture following Well-Architected Framework principles
      operationId: designArchitecture
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - job_name
                - requirements
              properties:
                job_name:
                  type: string
                  description: Unique job identifier
                requirements:
                  type: string
                  description: JSON string of requirements from Requirements Analyst
      responses:
        '200':
          description: Comprehensive architecture design completed
          content:
            application/json:
              schema:
                type: object
                required:
                  - job_name
                  - architecture
                  - status
                properties:
                  job_name:
                    type: string
                  architecture:
                    type: object
                    description: Customer-focused architecture design
                    properties:
                      executive_summary:
                        type: object
                      for_code_generator:
                        type: object
                        description: Service specifications and code patterns
                      for_quality_validator:
                        type: object
                        description: Security architecture and compliance framework
                      for_deployment_manager:
                        type: object
                        description: Infrastructure specifications and deployment topology
                      cost_analysis:
                        type: object
                        description: Cost estimates and optimization opportunities
                  status:
                    type: string
                    enum: [success, error]
