openapi: 3.0.0
info:
  title: Solution Architect Action Group API
  description: API for designing AWS architecture, selecting services, and generating infrastructure-as-code
  version: 1.0.0

paths:
  /design-architecture:
    post:
      summary: Design complete AWS architecture
      description: Creates comprehensive AWS architecture design based on requirements and code files
      operationId: designArchitecture
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - job_name
                - requirements
              properties:
                job_name:
                  type: string
                  description: Unique job identifier in format job-{keyword}-{YYYYMMDD-HHMMSS}
                requirements:
                  type: string
                  description: JSON string containing requirements from Requirements Analyst
                code_file_references:
                  type: string
                  description: JSON string containing references to code files from Code Generator
      responses:
        '200':
          description: Architecture successfully designed
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_name:
                    type: string
                    description: Job identifier
                  architecture:
                    type: string
                    description: JSON string containing complete architecture design
                  diagram:
                    type: string
                    description: Architecture diagram in text format
                  status:
                    type: string
                    description: Status of operation
        '400':
          description: Invalid request
        '500':
          description: Internal server error

  /select-services:
    post:
      summary: Select appropriate AWS services
      description: Analyzes requirements and selects optimal AWS services with rationale
      operationId: selectServices
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - job_name
                - requirements
              properties:
                job_name:
                  type: string
                  description: Unique job identifier
                requirements:
                  type: string
                  description: JSON string containing requirements from Requirements Analyst
      responses:
        '200':
          description: Services successfully selected
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_name:
                    type: string
                    description: Job identifier
                  services:
                    type: array
                    items:
                      type: string
                    description: List of selected AWS services
                  rationale:
                    type: string
                    description: JSON string containing justification for each service selection
                  status:
                    type: string
                    description: Status of operation
        '400':
          description: Invalid request
        '500':
          description: Internal server error

  /generate-iac:
    post:
      summary: Generate infrastructure-as-code templates
      description: Creates CloudFormation templates that reference Lambda code files and include all architecture components
      operationId: generateIac
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - job_name
                - architecture
              properties:
                job_name:
                  type: string
                  description: Unique job identifier
                architecture:
                  type: string
                  description: JSON string containing architecture design from design_architecture action
                code_references:
                  type: string
                  description: JSON string containing references to Lambda code and agent config files
      responses:
        '200':
          description: IaC templates successfully generated
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_name:
                    type: string
                    description: Job identifier
                  cloudformation_template:
                    type: string
                    description: CloudFormation template in YAML format
                  status:
                    type: string
                    description: Status of operation
        '400':
          description: Invalid request
        '500':
          description: Internal server error
