openapi: 3.0.0
info:
  title: Supervisor Orchestration API
  description: API for orchestrating multi-agent collaboration workflow
  version: 1.0.0

paths:
  /orchestrate:
    post:
      summary: Orchestrate agent collaboration workflow
      description: Orchestrates workflow across all 5 collaborator agents
      operationId: orchestrateAgents
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - user_request
              properties:
                user_request:
                  type: string
                  description: User request for agent creation
      responses:
        '200':
          description: Orchestration completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  job_name:
                    type: string
                  status:
                    type: string
                  agent_arn:
                    type: string

  # /getJobName:
  #   post:
  #     summary: Generate job name for a user request
  #     description: Returns the job_name that would be generated for a given user request without starting orchestration
  #     operationId: getJobName
  #     requestBody:
  #       required: true
  #       content:
  #         application/json:
  #           schema:
  #             type: object
  #             required:
  #               - user_request
  #             properties:
  #               user_request:
  #                 type: string
  #                 description: User request for agent creation
      # responses:
      #   '200':
      #     description: Job name generated
      #     content:
      #       application/json:
      #         schema:
      #           type: object
      #           required:
      #             - job_name
      #             - user_request
      #           properties:
      #             job_name:
      #               type: string
      #               description: Generated unique job identifier
      #             user_request:
      #               type: string
      #               description: Original user request
